import type { Language } from "./i18n";

const plural = (count: number, one: string, other: string) => (count === 1 ? one : other);

const it = {
  shell: {
    notFound: {
      order: {
        title: "Ordine non trovato",
        body: "L’ordine non esiste in questo account o non è più consultabile.",
        back: "Torna agli ordini",
      },
      store: {
        title: "Negozio non trovato",
        body: "Il negozio non è collegato a questo account.",
        back: "Torna ai negozi",
      },
      page: {
        title: "Pagina non trovata",
        body: "L’indirizzo non corrisponde a una pagina di FiscalBay.",
        back: "Torna agli ordini",
      },
    },
    skipToContent: "Vai al contenuto",
    mainNav: "Navigazione principale",
    orders: "Ordini",
    stores: "Negozi eBay",
    settings: "Impostazioni",
    search: "Cerca ordini",
    searchPlaceholder: "Ordine, acquirente, articolo o SKU",
    searchSeeAll: (count: number) => `Vedi tutti i risultati (${count})`,
    searchEmpty: "Nessun ordine corrisponde alla ricerca.",
    searchSummary: (count: number) =>
      count === 0
        ? "Nessun suggerimento"
        : `${count} ${plural(count, "suggerimento", "suggerimenti")}`,
    notifications: "Notifiche",
    notificationsUnread: (count: number) =>
      count === 0 ? "Notifiche" : `Notifiche, ${count} da leggere`,
    notificationsWindow: "Ultimi 30 giorni",
    notificationsEmpty: "Nessuna notifica negli ultimi 30 giorni.",
    markAllRead: "Segna tutte come lette",
    account: "Account",
    profile: "Profilo",
    security: "Sicurezza",
    planBilling: "Piano e pagamenti",
    visitSite: "Visita fiscalbay.it",
    signOut: "Esci",
    close: "Chiudi",
    back: "Indietro",
  },
  preview: {
    label: "Anteprima con dati di esempio",
    scenario: "Scenario",
    note: "Le azioni sono simulate: nessun negozio eBay viene letto o modificato e nessun ordine viene sbloccato davvero.",
    simulated: "Anteprima: l’azione è simulata.",
    signOut: "Anteprima: l’uscita è simulata.",
  },
  orders: {
    title: "Ordini",
    count: (count: number) => `${count} ${plural(count, "ordine", "ordini")}`,
    sortedBy: "Dal più recente",
    filters: "Filtri",
    store: "Negozio",
    marketplace: "Marketplace",
    period: "Periodo",
    paymentStatus: "Pagamento",
    shippingStatus: "Spedizione",
    fiscalStatus: "Dato fiscale",
    all: "Tutti",
    last7: "Ultimi 7 giorni",
    last30: "Ultimi 30 giorni",
    last90: "Ultimi 90 giorni",
    searchActive: (query: string) => `Ricerca: ${query}`,
    clearSearch: "Cancella ricerca",
    resetFilters: "Reimposta filtri",
    premiumOption: "Disponibile con Premium",
    payment: { paid: "Pagato", unpaid: "Non pagato", refunded: "Rimborsato" },
    shipping: {
      to_ship: "Da spedire",
      shipped: "Spedito",
      delivered: "Consegnato",
      cancelled: "Annullato",
    },
    billingAddress: "Indirizzo di fatturazione",
    phone: "Telefono",
    email: "Email",
    notProvided: "Non riportato da eBay",
    fiscal: {
      available: "Disponibile",
      locked: "Da sbloccare",
      missing: "Non disponibile su eBay",
      checking: "In verifica",
      error: "Aggiornamento non riuscito",
    },
    select: "Seleziona",
    cancelSelection: "Annulla",
    selectOrder: (id: string) => `Seleziona l’ordine ${id}`,
    selected: (count: number) => `${count} ${plural(count, "selezionato", "selezionati")}`,
    selectedLocked: (count: number) =>
      count === 0
        ? "Nessun ordine da sbloccare"
        : `${count} ${plural(count, "ordine da sbloccare", "ordini da sbloccare")}`,
    unlock: "Sblocca ordine",
    unlockSelected: (count: number) => `Sblocca ${count}`,
    exportSelected: "Esporta",
    unlockTitle: (count: number) => `Sbloccare ${count} ${plural(count, "ordine", "ordini")}?`,
    unlockConfirmText: (count: number, remaining: number) =>
      `Dopo lo sblocco ${plural(remaining - count, "ti resterà", "ti resteranno")} ${remaining - count} ${plural(remaining - count, "ordine", "ordini")} da sbloccare in questo ciclo.`,
    unlockExceeds: (count: number, remaining: number) =>
      `Hai selezionato ${count} ordini da sbloccare, ma in questo ciclo te ne ${plural(remaining, "resta", "restano")} ${remaining}. Riduci la selezione.`,
    unlockConfirm: "Sblocca",
    cancel: "Annulla",
    unlocked: (remaining: number | null) =>
      remaining === null
        ? "Ordine sbloccato."
        : `Ordine sbloccato. ${plural(remaining, "Ti resta", "Ti restano")} ${remaining} ${plural(remaining, "ordine", "ordini")} da sbloccare.`,
    unlockedMany: (count: number) => `${count} ordini sbloccati.`,
    loadMore: "Carica altri",
    allShown: "Hai visto tutti gli ordini del periodo.",
    importMore: "Importazione in corso: gli altri ordini compaiono qui man mano.",
    details: "Dettaglio",
    moreActions: (id: string) => `Altre azioni per l’ordine ${id}`,
    openOnEbay: "Apri su eBay",
    exportOrder: "Esporta ordine",
    exportNotice: "Anteprima: l’esportazione non crea file.",
    items: (count: number) => `${count} ${plural(count, "articolo", "articoli")}`,
    itemsMore: (count: number) => `+ ${count} ${plural(count, "altro articolo", "altri articoli")}`,
    quantity: "Quantità",
    newOrders: (count: number) => `${count} ${plural(count, "nuovo ordine", "nuovi ordini")}`,
    showNew: "Mostra",
    identifier: { CF: "Codice Fiscale", PIVA: "Partita IVA" },
    copy: (label: string, order: string) => `Copia ${label}: ordine ${order}`,
    copied: "Copiato negli appunti",
    copyFailed: "Copia non riuscita. Riprova oppure seleziona e copia il codice.",
    lockedLabel: "Dati fiscali da sbloccare",
    lockedHint: (remaining: number) =>
      `Sblocca tutti i dati fiscali di questo ordine. Hai ancora ${remaining} ${plural(remaining, "ordine disponibile", "ordini disponibili")}: dopo lo sblocco ${plural(remaining - 1, "ne resterà", "ne resteranno")} ${remaining - 1}.`,
    lockedExhausted: (date: string) =>
      `Hai sbloccato tutti gli ordini disponibili in questo ciclo. Il prossimo inizia il ${date}.`,
    lockedUntil: (date: string) => `Sblocco disponibile dal ${date}.`,
    missingHint: "eBay non riporta dati fiscali per questo ordine.",
    checkingHint: "Verifica dei dati fiscali in corso.",
    errorHint: "Non siamo riusciti a recuperare il Codice Fiscale da eBay. Riprova tra poco.",
    errorHintEbayDown:
      "Non siamo riusciti a recuperare il Codice Fiscale da eBay. Potrai riprovare quando eBay torna a rispondere.",
    retry: "Riprova",
    retried: "Nuova lettura richiesta.",
    quality: {
      format: "Il formato non corrisponde a un Codice Fiscale.",
      checksum: "Il carattere di controllo non corrisponde.",
      name: "Le lettere del codice non corrispondono al nome dell’ordine.",
      unverifiable: "Il nome non permette un controllo univoco del codice.",
      unchecked: "Tipo estero: FiscalBay non ne verifica il formato.",
    },
    toVerify: "Da verificare",
    updated: "Aggiornato da eBay",
    updatedHint: "eBay ha modificato questo dato dopo la prima lettura.",
    suggestion: "Suggerimento da un ordine precedente",
    suggestionFrom: "Da un ordine precedente:",
    suggestionCheck: "Verificalo nel dettaglio prima di usarlo.",
    suggestionHint: (order: string, date: string) =>
      `Dall’ordine ${order} del ${date}. Non sostituisce il dato di questo ordine.`,
    suggestionConflict: "Gli ordini precedenti riportano codici diversi: questo è il più recente.",
    requestMessage: "Copia messaggio per l’acquirente",
    requestCopied: "Messaggio copiato. Invialo all’acquirente dai tuoi canali.",
    syncedAgo: (time: string) => `Aggiornato ${time}`,
    refreshingTitle: "Aggiornamento in corso",
    ebayDownTitle: "eBay non risponde",
    ebayDownBody: (time: string) =>
      `Gli ordini sono aggiornati al ${time}. Sincronizzazione e ricollegamento tornano disponibili quando eBay risponde.`,
    quotaTitle: "Nessun ordine da sbloccare rimasto in questo ciclo",
    quotaBody: (date: string) =>
      `Puoi consultare e cercare tutti gli ordini. I dati fiscali dei nuovi ordini restano da sbloccare fino al ${date}.`,
    quotaAction: "Scopri Premium",
    storeIssueTitle: (store: string) => `${store}: collegamento scaduto`,
    storeIssueBody:
      "La sincronizzazione di questo negozio è sospesa; gli altri negozi continuano. Ricollega il negozio.",
    storeIssueAction: "Apri il negozio",
    importingStatus: (count: number) =>
      `Importazione in corso: ${count} ${plural(count, "ordine", "ordini")} finora`,
    firstUseTitle: "Nessun negozio collegato",
    firstUseBody:
      "Collega il tuo negozio eBay per consultare gli ordini e i Codici Fiscali disponibili.",
    connectStore: "Collega negozio eBay",
    steps: "Primi passi",
    stepAccount: "Account creato",
    stepEmail: "Email verificata",
    stepStore: "Negozio eBay collegato",
    stepSync: "Prima sincronizzazione",
    noOrdersTitle: "Nessun ordine negli ultimi 30 giorni",
    noOrdersBody: (store: string, time: string) =>
      `${store} è collegato e aggiornato al ${time}. I nuovi ordini compariranno qui.`,
    openStore: "Apri il negozio",
    noResultsTitle: "Nessun risultato",
    noResultsBody: "Nessun ordine corrisponde ai filtri. Modifica i criteri di ricerca.",
    noSearchResultsBody:
      "Nessun ordine corrisponde alla ricerca. Controlla il testo o cerca per numero d’ordine, acquirente, articolo o SKU.",
    loading: "Caricamento degli ordini",
    list: "Elenco ordini",
  },
  order: {
    title: (id: string) => `Ordine ${id}`,
    tabDetails: "Dettagli",
    tabItems: "Articoli",
    fiscal: "Dati fiscali",
    source: (time: string) => `Fonte: eBay, letto il ${time}`,
    buyer: "Acquirente",
    username: "Nome utente eBay",
    shipping: "Spedizione",
    recipient: "Destinatario",
    summary: "Ordine",
    total: "Totale",
    store: "Negozio",
    marketplace: "Marketplace",
    created: "Data ordine",
    update: "Aggiornamento",
    lastSynced: (time: string) => `Ultima lettura da eBay: ${time}`,
    sku: "SKU",
    noSku: "Senza SKU",
    price: "Prezzo",
  },
  stores: {
    title: "Negozi eBay",
    list: "Elenco negozi",
    connect: "Collega negozio eBay",
    store: "Negozio",
    marketplace: "Marketplace",
    connection: "Collegamento",
    lastSync: "Ultima sincronizzazione",
    openDetail: "Apri",
    notifications: "Notifiche",
    orders: "Ordini importati",
    state: {
      active: "Collegato",
      paused: "In pausa",
      reconnect_required: "Da ricollegare",
      error: "Autorizzazione incompleta",
    },
    syncing: "In sincronizzazione",
    never: "Mai",
    pausedByPlan: "In pausa per il piano Free",
    notificationsOn: "Attive",
    notificationsOff: "Disattivate",
    notificationsFree: "Le notifiche Telegram dei nuovi ordini sono disponibili con Premium.",
    freeLimit:
      "Con il piano Free hai un negozio attivo e puoi sostituirlo ogni 90 giorni. Gli altri restano in pausa e i loro ordini non sono consultabili.",
    open: (name: string) => `Apri ${name}`,
    sectionConnection: "Collegamento",
    sectionSync: "Sincronizzazione",
    sectionNotifications: "Notifiche",
    sectionRecent: "Ultimi aggiornamenti",
    sectionActions: "Azioni",
    account: "Account eBay",
    connectedSince: "Collegato dal",
    consentUntil: "Autorizzazione valida fino al",
    consentHint: "Prima della scadenza ti chiederemo di ricollegare il negozio.",
    consentExpired: "Scaduta",
    target: (minutes: number) => `Aggiornamento previsto circa ogni ${minutes} minuti`,
    history: (days: number) => `Storico degli ultimi ${days} giorni`,
    importDone: "Importazione dello storico completata",
    importRunning: "Importazione dello storico in corso",
    recentOk: (count: number) =>
      count === 0
        ? "Riuscito, nessun nuovo ordine"
        : `Riuscito, ${count} ${plural(count, "nuovo ordine", "nuovi ordini")}`,
    recentFailed: "Non riuscito",
    notificationsShortcut: "Le notifiche dei negozi si impostano in Impostazioni.",
    notificationsLink: "Apri le notifiche",
    syncNow: "Sincronizza ordini recenti",
    reimport: "Reimporta storico",
    pause: "Metti in pausa",
    resume: "Riprendi",
    pauseHint:
      "In pausa FiscalBay non legge nuovi ordini; quelli già importati restano consultabili.",
    planPauseHint:
      "Il piano Free include un solo negozio attivo. Scegli quale in Piano e pagamenti.",
    reconnect: "Ricollega negozio",
    disconnect: "Scollega",
    disconnectDelete: "Scollega ed elimina dati",
    disconnectTitle: (name: string) => `Scollegare ${name}?`,
    disconnectBody:
      "FiscalBay smette di leggere il negozio su eBay. Gli ordini già importati restano consultabili per il periodo di conservazione e puoi ricollegare lo stesso negozio in seguito.",
    deleteTitle: (name: string) => `Scollegare ed eliminare i dati di ${name}?`,
    deleteBody:
      "Il negozio viene scollegato e tutti i suoi ordini vengono eliminati da FiscalBay. L’operazione non si può annullare.",
    deleteLabel: "Scrivi il nome del negozio per confermare",
    deleteConfirm: "Scollega ed elimina",
    cancel: "Annulla",
    issue: {
      reconnect: {
        title: "Collegamento scaduto",
        body: "La sincronizzazione è sospesa. Ricollega il negozio.",
      },
      permissions: {
        title: "Autorizzazione incompleta",
        body: "eBay non ha concesso l’accesso agli ordini. Ricollega il negozio e accetta tutte le autorizzazioni richieste.",
      },
      unverifiable: {
        title: "Negozio non verificabile",
        body: "eBay non conferma l’identità di questo negozio. La sincronizzazione è sospesa. Ricollega il negozio; se il problema continua, contatta l’assistenza.",
      },
    },
    elsewhereTitle: "Negozio già collegato a un altro account",
    elsewhereBody:
      "Questo negozio eBay è collegato a un altro account FiscalBay. Accedi con quell’account oppure contatta l’assistenza.",
    ebayDown: "eBay non risponde: sincronizzazione e ricollegamento sono sospesi.",
  },
  settings: {
    title: "Impostazioni",
    categories: "Categorie",
    sections: {
      piano: { title: "Piano e pagamenti", description: "Piano, ordini da sbloccare e pagamenti" },
      notifiche: { title: "Notifiche", description: "Telegram e comunicazioni" },
      esportazione: { title: "Esportazione", description: "File CSV e XLSX degli ordini" },
      sicurezza: { title: "Sicurezza", description: "Metodi di accesso e sessioni" },
      aspetto: { title: "Aspetto e lingua", description: "Tema, lingua e fuso orario" },
      messaggio: {
        title: "Modello di messaggio",
        description: "Richiesta dei dati fiscali all’acquirente",
      },
      privacy: {
        title: "Dati e privacy",
        description: "Informativa, esportazione e cancellazione",
      },
      supporto: { title: "Supporto", description: "Domande frequenti e assistenza" },
    },
    premiumBadge: "Premium",
    saving: "Salvataggio…",
    saved: "Salvato",
    saveFailed: "Modifica non salvata. L’impostazione è tornata com’era: riprova.",
    save: "Salva",
    // Piano e pagamenti
    currentPlan: "Piano attuale",
    free: "Free",
    premium: "Premium",
    freeSummary: "Un negozio attivo, ultimi 30 giorni di ordini, CSV.",
    unlocksCycle: "Ordini sbloccati in questo ciclo",
    unlocksUsed: (used: number, limit: number) => `${used} di ${limit}`,
    cycleEnds: (date: string) => `Il ciclo si rinnova il ${date}.`,
    trialTitle: "Prova Premium per 14 giorni",
    trialBody:
      "Senza carta e senza rinnovo automatico: alla fine torni al piano Free, a meno che tu non acquisti.",
    trialAction: "Attiva la prova",
    buyTitle: "Passa a Premium",
    buyBody:
      "Ordini da sbloccare senza limite per ciclo, più negozi attivi, un anno di storico, XLSX e notifiche Telegram.",
    priceMonthly: "4,90 € al mese",
    priceAnnual: "49 € all’anno",
    priceLifetime: "149 € una tantum",
    priceMonthlyNote: "Si rinnova ogni mese.",
    priceAnnualNote: "Equivale a 4,08 € al mese.",
    priceLifetimeNote: "Pagamento unico, senza rinnovi.",
    pricesNote: "Prezzi IVA esclusa. Il pagamento avviene su Stripe.",
    buy: "Scegli",
    premiumPeriod: {
      monthly: "Premium mensile",
      annual: "Premium annuale",
      lifetime: "Premium a vita",
    },
    premiumLifetime: "Acquisto una tantum, senza rinnovi.",
    premiumRenews: (date: string) => `Si rinnova il ${date}.`,
    manageBilling: "Gestisci abbonamento su Stripe",
    billingDocs: "Ricevute e fatture sono disponibili su Stripe.",
    downgradeStore: "Negozio attivo se torni al piano Free",
    downgradeStoreHint:
      "Gli altri negozi andranno in pausa. Puoi cambiare scelta in qualsiasi momento.",
    // Notifiche
    telegramTitle: "Notifiche Telegram",
    telegramPremium: "Le notifiche degli ordini su Telegram sono incluse in Premium.",
    telegramChat: "Chat collegata",
    telegramChange: "Cambia chat",
    telegramEnabled: "Invia notifiche degli ordini",
    telegramFilter: "Quali ordini",
    telegramFilterAll: "Tutti i nuovi ordini",
    telegramFilterFiscal: "Solo ordini con dati fiscali",
    telegramMode: "Frequenza",
    telegramModeEach: "Un messaggio per ordine",
    telegramModeDigest: "Riepilogo giornaliero",
    telegramDigestTime: "Orario del riepilogo",
    telegramStores: "Negozi",
    marketingTitle: "Comunicazioni",
    marketingConsent: "Ricevi via email novità e offerte su FiscalBay",
    marketingHint: "Facoltativo. Le email di servizio e di sicurezza arrivano comunque.",
    // Esportazione
    exportScope: "Ordini da esportare",
    exportPeriod: "Periodo",
    exportStores: "Negozi",
    exportFormat: "Formato",
    exportRows: "Una riga per",
    exportRowOrder: "Ordine",
    exportRowItem: "Articolo",
    exportColumns: "Colonne",
    exportColumnsPremium: "Colonne selezionabili e ordinabili con Premium.",
    exportPreview: (orders: number, locked: number) =>
      locked === 0
        ? `Circa ${orders} ordini.`
        : `Circa ${orders} ordini. I dati fiscali di ${locked} ${plural(locked, "ordine da sbloccare restano vuoti", "ordini da sbloccare restano vuoti")}.`,
    exportCreate: "Crea file",
    exportCreated: "Anteprima: nessun file creato. Il file reale resta scaricabile per 24 ore.",
    exportSaveConfig: "Salva configurazione",
    columns: {
      order: "Numero ordine",
      date: "Data",
      buyer: "Acquirente",
      taxCode: "Codice Fiscale",
      vat: "Partita IVA",
      total: "Totale",
      store: "Negozio",
    },
    // Sicurezza
    methods: "Metodi di accesso",
    methodPassword: "Email e password",
    methodGoogle: "Google",
    methodEbay: "eBay",
    methodPasskey: "Passkey",
    methodConnected: "Collegato",
    methodNotConnected: "Non collegato",
    changePassword: "Cambia password",
    connect: "Collega",
    remove: "Rimuovi",
    addPasskey: "Aggiungi passkey",
    passkeyItem: (device: string, date: string) => `${device}, aggiunta il ${date}`,
    lastMethod: "Serve almeno un metodo di accesso.",
    sessions: "Sessioni attive",
    thisDevice: "Questo dispositivo",
    lastActive: (time: string) => `Ultima attività ${time}`,
    signOutSession: "Esci",
    signOutAll: "Esci da tutti gli altri dispositivi",
    // Aspetto e lingua
    theme: "Tema",
    themeSystem: "Sistema",
    themeLight: "Chiaro",
    themeDark: "Scuro",
    themeNote: "Nell’anteprima la scelta vale fino alla chiusura della pagina.",
    language: "Lingua",
    timeZone: "Fuso orario",
    timeZoneHint: "Usato per date, cicli e orari delle notifiche.",
    // Modello di messaggio
    templateIntro:
      "Quando eBay non riporta un dato fiscale, puoi copiare questo messaggio dall’ordine e inviarlo all’acquirente dai tuoi canali. FiscalBay non lo invia.",
    templateIt: "Italiano",
    templateEn: "Inglese",
    templateHint: "{ordine} viene sostituito con il numero dell’ordine.",
    templateDefaultIt:
      "Buongiorno, per completare la documentazione dell’ordine {ordine} ci serve il tuo Codice Fiscale. Puoi rispondere a questo messaggio indicandolo? Grazie.",
    templateDefaultEn:
      "Hello, to complete the paperwork for order {ordine} we need your Italian tax code (Codice Fiscale). Could you reply to this message with it? Thank you.",
    // Dati e privacy
    privacyPolicy: "Informativa privacy",
    privacyPolicyBody: "Quali dati trattiamo, per quanto tempo e con quali fornitori.",
    accountExport: "Esporta i dati dell’account",
    accountExportBody: "Profilo, negozi e impostazioni in un file scaricabile.",
    accountExportAction: "Richiedi esportazione",
    deleteAccount: "Elimina account",
    deleteAccountBody:
      "Elimina l’account, scollega i negozi e cancella gli ordini importati. Per confermare ti chiederemo di accedere di nuovo.",
    deleteAccountTitle: "Eliminare l’account?",
    deleteAccountConfirm: "Continua",
    // Supporto
    faq: "Domande frequenti",
    faqItems: [
      {
        q: "Perché un ordine non ha il Codice Fiscale?",
        a: "eBay non lo riporta per tutti gli ordini. Quando manca, puoi chiederlo all’acquirente con il modello di messaggio.",
      },
      {
        q: "Quando un ordine conta come sbloccato?",
        a: "Solo quando almeno un suo dato fiscale diventa visibile. Dati non disponibili, errori, copie ed esportazioni non contano.",
      },
      {
        q: "FiscalBay modifica gli ordini su eBay?",
        a: "No. FiscalBay legge gli ordini e non scrive nulla sul tuo negozio.",
      },
    ],
    contact: "Scrivi all’assistenza",
    topic: "Argomento",
    topics: {
      orders: "Ordini e dati fiscali",
      stores: "Collegamento negozi",
      billing: "Piano e pagamenti",
      other: "Altro",
    },
    message: "Messaggio",
    messageRequired: "Scrivi il messaggio.",
    diagnostics: "Riepilogo diagnostico",
    diagnosticsHint:
      "Aiuta l’assistenza a capire il problema. Non contiene Codici Fiscali, dati degli acquirenti o credenziali.",
    includeDiagnostics: "Allega il riepilogo diagnostico",
    diag: {
      version: "Versione",
      store: "Negozio",
      sync: "Sincronizzazione",
      error: "Codice errore",
      rights: "Piano",
      reference: "Riferimento",
      none: "Nessuno",
    },
    send: "Invia",
    sent: (email: string) => `Anteprima: richiesta non inviata. Ti risponderemmo a ${email}.`,
    formErrors: "Correggi i campi evidenziati.",
    supportEmail: "Puoi scrivere anche a supporto@fiscalbay.it.",
  },
  profile: {
    title: "Profilo",
    name: "Nome",
    nameHint: "Facoltativo. Compare nelle email di servizio.",
    email: "Email",
    emailHint: "Per cambiarla ti invieremo un link di verifica al nuovo indirizzo.",
    changeEmail: "Cambia email",
    security: "Metodi di accesso e sessioni sono in Sicurezza.",
    securityLink: "Apri Sicurezza",
    saved: "Anteprima: profilo non salvato.",
  },
};

export type AppCopy = typeof it;

const en: AppCopy = {
  shell: {
    notFound: {
      order: {
        title: "Order not found",
        body: "The order does not exist in this account or is no longer available.",
        back: "Back to orders",
      },
      store: {
        title: "Store not found",
        body: "The store is not connected to this account.",
        back: "Back to stores",
      },
      page: {
        title: "Page not found",
        body: "The address does not match a FiscalBay page.",
        back: "Back to orders",
      },
    },
    skipToContent: "Skip to content",
    mainNav: "Main navigation",
    orders: "Orders",
    stores: "eBay stores",
    settings: "Settings",
    search: "Search orders",
    searchPlaceholder: "Order, buyer, item or SKU",
    searchSeeAll: (count) => `See all results (${count})`,
    searchEmpty: "No orders match your search.",
    searchSummary: (count) =>
      count === 0 ? "No suggestions" : `${count} ${plural(count, "suggestion", "suggestions")}`,
    notifications: "Notifications",
    notificationsUnread: (count) =>
      count === 0 ? "Notifications" : `Notifications, ${count} unread`,
    notificationsWindow: "Last 30 days",
    notificationsEmpty: "No notifications in the last 30 days.",
    markAllRead: "Mark all as read",
    account: "Account",
    profile: "Profile",
    security: "Security",
    planBilling: "Plan and billing",
    visitSite: "Visit fiscalbay.it",
    signOut: "Sign out",
    close: "Close",
    back: "Back",
  },
  preview: {
    label: "Preview with sample data",
    scenario: "Scenario",
    note: "Actions are simulated: no eBay store is read or changed and no order is actually unlocked.",
    simulated: "Preview: this action is simulated.",
    signOut: "Preview: signing out is simulated.",
  },
  orders: {
    title: "Orders",
    count: (count) => `${count} ${plural(count, "order", "orders")}`,
    sortedBy: "Newest first",
    filters: "Filters",
    store: "Store",
    marketplace: "Marketplace",
    period: "Period",
    paymentStatus: "Payment",
    shippingStatus: "Shipping",
    fiscalStatus: "Tax data",
    all: "All",
    last7: "Last 7 days",
    last30: "Last 30 days",
    last90: "Last 90 days",
    searchActive: (query) => `Search: ${query}`,
    clearSearch: "Clear search",
    resetFilters: "Reset filters",
    premiumOption: "Available with Premium",
    payment: { paid: "Paid", unpaid: "Unpaid", refunded: "Refunded" },
    shipping: {
      to_ship: "To ship",
      shipped: "Shipped",
      delivered: "Delivered",
      cancelled: "Cancelled",
    },
    billingAddress: "Billing address",
    phone: "Phone",
    email: "Email",
    notProvided: "Not provided by eBay",
    fiscal: {
      available: "Available",
      locked: "To unlock",
      missing: "Not available on eBay",
      checking: "Checking",
      error: "Couldn’t update",
    },
    select: "Select",
    cancelSelection: "Cancel",
    selectOrder: (id) => `Select order ${id}`,
    selected: (count) => `${count} selected`,
    selectedLocked: (count) =>
      count === 0
        ? "No orders to unlock"
        : `${count} ${plural(count, "order to unlock", "orders to unlock")}`,
    unlock: "Unlock order",
    unlockSelected: (count) => `Unlock ${count}`,
    exportSelected: "Export",
    unlockTitle: (count) => `Unlock ${count} ${plural(count, "order", "orders")}?`,
    unlockConfirmText: (count, remaining) =>
      `After unlocking, you can unlock ${remaining - count} more ${plural(remaining - count, "order", "orders")} this cycle.`,
    unlockExceeds: (count, remaining) =>
      `You selected ${count} orders to unlock, but you can unlock ${remaining} more ${plural(remaining, "order", "orders")} this cycle. Reduce the selection.`,
    unlockConfirm: "Unlock",
    cancel: "Cancel",
    unlocked: (remaining) =>
      remaining === null
        ? "Order unlocked."
        : `Order unlocked. You can unlock ${remaining} more ${plural(remaining, "order", "orders")}.`,
    unlockedMany: (count) => `${count} orders unlocked.`,
    loadMore: "Load more",
    allShown: "You have seen all orders in this period.",
    importMore: "Import in progress: the remaining orders will appear here as they arrive.",
    details: "Details",
    moreActions: (id) => `More actions for order ${id}`,
    openOnEbay: "Open on eBay",
    exportOrder: "Export order",
    exportNotice: "Preview: exporting does not create a file.",
    items: (count) => `${count} ${plural(count, "item", "items")}`,
    itemsMore: (count) => `+ ${count} more ${plural(count, "item", "items")}`,
    quantity: "Quantity",
    newOrders: (count) => `${count} new ${plural(count, "order", "orders")}`,
    showNew: "Show",
    identifier: { CF: "Codice Fiscale", PIVA: "Partita IVA" },
    copy: (label, order) => `Copy ${label}: order ${order}`,
    copied: "Copied to clipboard",
    copyFailed: "Copy failed. Try again, or select and copy the code.",
    lockedLabel: "Tax data to unlock",
    lockedHint: (remaining) =>
      `Unlock all tax details for this order. You have ${remaining} ${plural(remaining, "order", "orders")} left; after unlocking, you will have ${remaining - 1}.`,
    lockedExhausted: (date) =>
      `You have unlocked all available orders this cycle. The next one starts on ${date}.`,
    lockedUntil: (date) => `Unlocking available from ${date}.`,
    missingHint: "eBay does not provide tax details for this order.",
    checkingHint: "Checking the tax details.",
    errorHint: "We could not get the tax code from eBay. Try again shortly.",
    errorHintEbayDown:
      "We could not get the tax code from eBay. You can try again once eBay responds.",
    retry: "Try again",
    retried: "New read requested.",
    quality: {
      format: "The format does not match an Italian tax code.",
      checksum: "The check character does not match.",
      name: "The letters of the code do not match the name on the order.",
      unverifiable: "The name does not allow an unambiguous check of the code.",
      unchecked: "Foreign type: FiscalBay does not check its format.",
    },
    toVerify: "Needs review",
    updated: "Updated by eBay",
    updatedHint: "eBay changed this value after it was first read.",
    suggestion: "Suggestion from a previous order",
    suggestionFrom: "From a previous order:",
    suggestionCheck: "Check it in the details before using it.",
    suggestionHint: (order, date) =>
      `From order ${order} on ${date}. It does not replace the value for this order.`,
    suggestionConflict: "Previous orders show different codes: this is the most recent.",
    requestMessage: "Copy message for the buyer",
    requestCopied: "Message copied. Send it to the buyer through your own channels.",
    syncedAgo: (time) => `Updated ${time}`,
    refreshingTitle: "Updating",
    ebayDownTitle: "eBay is not responding",
    ebayDownBody: (time) =>
      `Orders are up to date as of ${time}. Syncing and reconnecting will be available again when eBay responds.`,
    quotaTitle: "No orders left to unlock this cycle",
    quotaBody: (date) =>
      `You can still view and search all orders. Tax details of new orders stay locked until ${date}.`,
    quotaAction: "Discover Premium",
    storeIssueTitle: (store) => `${store}: connection expired`,
    storeIssueBody: "Syncing is paused for this store; other stores continue. Reconnect the store.",
    storeIssueAction: "Open store",
    importingStatus: (count) => `Importing: ${count} ${plural(count, "order", "orders")} so far`,
    firstUseTitle: "No store connected",
    firstUseBody: "Connect your eBay store to view orders and available tax codes.",
    connectStore: "Connect eBay store",
    steps: "Getting started",
    stepAccount: "Account created",
    stepEmail: "Email verified",
    stepStore: "eBay store connected",
    stepSync: "First sync",
    noOrdersTitle: "No orders in the last 30 days",
    noOrdersBody: (store, time) =>
      `${store} is connected and up to date as of ${time}. New orders will appear here.`,
    openStore: "Open store",
    noResultsTitle: "No results",
    noResultsBody: "No orders match the filters. Change your search criteria.",
    noSearchResultsBody:
      "No orders match the search. Check the text or search by order number, buyer, item or SKU.",
    loading: "Loading orders",
    list: "Order list",
  },
  order: {
    title: (id) => `Order ${id}`,
    tabDetails: "Details",
    tabItems: "Items",
    fiscal: "Tax details",
    source: (time) => `Source: eBay, read on ${time}`,
    buyer: "Buyer",
    username: "eBay username",
    shipping: "Shipping",
    recipient: "Recipient",
    summary: "Order",
    total: "Total",
    store: "Store",
    marketplace: "Marketplace",
    created: "Order date",
    update: "Update",
    lastSynced: (time) => `Last read from eBay: ${time}`,
    sku: "SKU",
    noSku: "No SKU",
    price: "Price",
  },
  stores: {
    title: "eBay stores",
    list: "Store list",
    connect: "Connect eBay store",
    store: "Store",
    marketplace: "Marketplace",
    connection: "Connection",
    lastSync: "Last sync",
    openDetail: "Open",
    notifications: "Notifications",
    orders: "Imported orders",
    state: {
      active: "Connected",
      paused: "Paused",
      reconnect_required: "Reconnect needed",
      error: "Incomplete authorisation",
    },
    syncing: "Syncing",
    never: "Never",
    pausedByPlan: "Paused on the Free plan",
    notificationsOn: "On",
    notificationsOff: "Off",
    notificationsFree: "Telegram notifications for new orders are available with Premium.",
    freeLimit:
      "On the Free plan you have one active store, which you can replace every 90 days. Other stores stay paused and their orders are not available.",
    open: (name) => `Open ${name}`,
    sectionConnection: "Connection",
    sectionSync: "Sync",
    sectionNotifications: "Notifications",
    sectionRecent: "Recent updates",
    sectionActions: "Actions",
    account: "eBay account",
    connectedSince: "Connected since",
    consentUntil: "Authorisation valid until",
    consentHint: "Before it expires we will ask you to reconnect the store.",
    consentExpired: "Expired",
    target: (minutes) => `Expected update about every ${minutes} minutes`,
    history: (days) => `History of the last ${days} days`,
    importDone: "History import complete",
    importRunning: "History import in progress",
    recentOk: (count) =>
      count === 0
        ? "Succeeded, no new orders"
        : `Succeeded, ${count} new ${plural(count, "order", "orders")}`,
    recentFailed: "Failed",
    notificationsShortcut: "Store notifications are set in Settings.",
    notificationsLink: "Open notifications",
    syncNow: "Sync recent orders",
    reimport: "Re-import history",
    pause: "Pause",
    resume: "Resume",
    pauseHint: "While paused, FiscalBay reads no new orders; imported orders remain available.",
    planPauseHint: "The Free plan includes one active store. Choose it in Plan and billing.",
    reconnect: "Reconnect store",
    disconnect: "Disconnect",
    disconnectDelete: "Disconnect and delete data",
    disconnectTitle: (name) => `Disconnect ${name}?`,
    disconnectBody:
      "FiscalBay will stop reading this store on eBay. Imported orders remain available for the retention period and you can reconnect the same store later.",
    deleteTitle: (name) => `Disconnect ${name} and delete its data?`,
    deleteBody:
      "The store is disconnected and all its orders are deleted from FiscalBay. This cannot be undone.",
    deleteLabel: "Type the store name to confirm",
    deleteConfirm: "Disconnect and delete",
    cancel: "Cancel",
    issue: {
      reconnect: {
        title: "Connection expired",
        body: "Syncing is paused. Reconnect the store.",
      },
      permissions: {
        title: "Incomplete authorisation",
        body: "eBay did not grant access to orders. Reconnect the store and accept all requested permissions.",
      },
      unverifiable: {
        title: "Store cannot be verified",
        body: "eBay does not confirm this store’s identity. Syncing is paused. Reconnect the store; if the problem continues, contact support.",
      },
    },
    elsewhereTitle: "Store already connected to another account",
    elsewhereBody:
      "This eBay store is connected to another FiscalBay account. Sign in with that account or contact support.",
    ebayDown: "eBay is not responding: syncing and reconnecting are paused.",
  },
  settings: {
    title: "Settings",
    categories: "Categories",
    sections: {
      piano: { title: "Plan and billing", description: "Plan, orders to unlock and payments" },
      notifiche: { title: "Notifications", description: "Telegram and communications" },
      esportazione: { title: "Export", description: "CSV and XLSX order files" },
      sicurezza: { title: "Security", description: "Sign-in methods and sessions" },
      aspetto: { title: "Appearance and language", description: "Theme, language and time zone" },
      messaggio: { title: "Message template", description: "Asking the buyer for tax details" },
      privacy: { title: "Data and privacy", description: "Policy, export and deletion" },
      supporto: { title: "Support", description: "FAQ and help" },
    },
    premiumBadge: "Premium",
    saving: "Saving…",
    saved: "Saved",
    saveFailed: "Change not saved. The setting has been restored: try again.",
    save: "Save",
    currentPlan: "Current plan",
    free: "Free",
    premium: "Premium",
    freeSummary: "One active store, the last 30 days of orders, CSV.",
    unlocksCycle: "Orders unlocked this cycle",
    unlocksUsed: (used, limit) => `${used} of ${limit}`,
    cycleEnds: (date) => `The cycle renews on ${date}.`,
    trialTitle: "Try Premium for 14 days",
    trialBody: "No card and no automatic renewal: at the end you return to Free unless you buy.",
    trialAction: "Start trial",
    buyTitle: "Upgrade to Premium",
    buyBody:
      "No limit on orders to unlock per cycle, more active stores, one year of history, XLSX and Telegram notifications.",
    priceMonthly: "€4.90 per month",
    priceAnnual: "€49 per year",
    priceLifetime: "€149 one-off",
    priceMonthlyNote: "Renews every month.",
    priceAnnualNote: "Works out at €4.08 per month.",
    priceLifetimeNote: "One-off payment, no renewals.",
    pricesNote: "Prices exclude VAT. Payment takes place on Stripe.",
    buy: "Choose",
    premiumPeriod: {
      monthly: "Premium, monthly",
      annual: "Premium, annual",
      lifetime: "Premium, lifetime",
    },
    premiumLifetime: "One-off purchase, no renewals.",
    premiumRenews: (date) => `Renews on ${date}.`,
    manageBilling: "Manage subscription on Stripe",
    billingDocs: "Receipts and invoices are available on Stripe.",
    downgradeStore: "Active store if you return to Free",
    downgradeStoreHint: "Other stores will be paused. You can change this at any time.",
    telegramTitle: "Telegram notifications",
    telegramPremium: "Order notifications on Telegram are included in Premium.",
    telegramChat: "Connected chat",
    telegramChange: "Change chat",
    telegramEnabled: "Send order notifications",
    telegramFilter: "Which orders",
    telegramFilterAll: "All new orders",
    telegramFilterFiscal: "Only orders with tax details",
    telegramMode: "Frequency",
    telegramModeEach: "One message per order",
    telegramModeDigest: "Daily summary",
    telegramDigestTime: "Summary time",
    telegramStores: "Stores",
    marketingTitle: "Communications",
    marketingConsent: "Receive FiscalBay news and offers by email",
    marketingHint: "Optional. Service and security emails are always sent.",
    exportScope: "Orders to export",
    exportPeriod: "Period",
    exportStores: "Stores",
    exportFormat: "Format",
    exportRows: "One row per",
    exportRowOrder: "Order",
    exportRowItem: "Item",
    exportColumns: "Columns",
    exportColumnsPremium: "Choose and reorder columns with Premium.",
    exportPreview: (orders, locked) =>
      locked === 0
        ? `About ${orders} orders.`
        : `About ${orders} orders. Tax details of ${locked} ${plural(locked, "order to unlock stay", "orders to unlock stay")} empty.`,
    exportCreate: "Create file",
    exportCreated: "Preview: no file created. A real file stays available for 24 hours.",
    exportSaveConfig: "Save configuration",
    columns: {
      order: "Order number",
      date: "Date",
      buyer: "Buyer",
      taxCode: "Codice Fiscale",
      vat: "Partita IVA",
      total: "Total",
      store: "Store",
    },
    methods: "Sign-in methods",
    methodPassword: "Email and password",
    methodGoogle: "Google",
    methodEbay: "eBay",
    methodPasskey: "Passkey",
    methodConnected: "Connected",
    methodNotConnected: "Not connected",
    changePassword: "Change password",
    connect: "Connect",
    remove: "Remove",
    addPasskey: "Add passkey",
    passkeyItem: (device, date) => `${device}, added on ${date}`,
    lastMethod: "At least one sign-in method is required.",
    sessions: "Active sessions",
    thisDevice: "This device",
    lastActive: (time) => `Last active ${time}`,
    signOutSession: "Sign out",
    signOutAll: "Sign out of all other devices",
    theme: "Theme",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    themeNote: "In the preview, the choice lasts until you close the page.",
    language: "Language",
    timeZone: "Time zone",
    timeZoneHint: "Used for dates, cycles and notification times.",
    templateIntro:
      "When eBay does not provide tax details, you can copy this message from the order and send it to the buyer through your own channels. FiscalBay does not send it.",
    templateIt: "Italian",
    templateEn: "English",
    templateHint: "{ordine} is replaced with the order number.",
    templateDefaultIt:
      "Buongiorno, per completare la documentazione dell’ordine {ordine} ci serve il tuo Codice Fiscale. Puoi rispondere a questo messaggio indicandolo? Grazie.",
    templateDefaultEn:
      "Hello, to complete the paperwork for order {ordine} we need your Italian tax code (Codice Fiscale). Could you reply to this message with it? Thank you.",
    privacyPolicy: "Privacy policy",
    privacyPolicyBody: "What data we process, for how long and with which providers.",
    accountExport: "Export account data",
    accountExportBody: "Profile, stores and settings in a downloadable file.",
    accountExportAction: "Request export",
    deleteAccount: "Delete account",
    deleteAccountBody:
      "Deletes the account, disconnects your stores and erases imported orders. To confirm, we will ask you to sign in again.",
    deleteAccountTitle: "Delete your account?",
    deleteAccountConfirm: "Continue",
    faq: "Frequently asked questions",
    faqItems: [
      {
        q: "Why does an order have no Codice Fiscale?",
        a: "eBay does not provide it for every order. When it is missing, you can ask the buyer with the message template.",
      },
      {
        q: "When does an order count as unlocked?",
        a: "Only when at least one of its tax details becomes visible. Unavailable data, errors, copies and exports do not count.",
      },
      {
        q: "Does FiscalBay change orders on eBay?",
        a: "No. FiscalBay reads orders and writes nothing to your store.",
      },
    ],
    contact: "Contact support",
    topic: "Topic",
    topics: {
      orders: "Orders and tax details",
      stores: "Store connection",
      billing: "Plan and billing",
      other: "Other",
    },
    message: "Message",
    messageRequired: "Write your message.",
    diagnostics: "Diagnostic summary",
    diagnosticsHint:
      "Helps support understand the problem. It contains no tax codes, buyer data or credentials.",
    includeDiagnostics: "Attach the diagnostic summary",
    diag: {
      version: "Version",
      store: "Store",
      sync: "Sync",
      error: "Error code",
      rights: "Plan",
      reference: "Reference",
      none: "None",
    },
    send: "Send",
    sent: (email) => `Preview: request not sent. We would reply to ${email}.`,
    formErrors: "Fix the highlighted fields.",
    supportEmail: "You can also write to supporto@fiscalbay.it.",
  },
  profile: {
    title: "Profile",
    name: "Name",
    nameHint: "Optional. Shown in service emails.",
    email: "Email",
    emailHint: "To change it, we will send a verification link to the new address.",
    changeEmail: "Change email",
    security: "Sign-in methods and sessions are in Security.",
    securityLink: "Open Security",
    saved: "Preview: profile not saved.",
  },
};

export const appCopy: Record<Language, AppCopy> = { it, en };
