import type { Language } from "./i18n";

const plural = (count: number, one: string, other: string) => (count === 1 ? one : other);

const it = {
  shell: {
    notFound: {
      order: {
        title: "Ordine non trovato",
        body: "L’ordine non esiste in questo account o non è più consultabile.",
        back: "Torna agli ordini",
      },
      store: {
        title: "Negozio non trovato",
        body: "Il negozio non è collegato a questo account.",
        back: "Torna ai negozi",
      },
      page: {
        title: "Pagina non trovata",
        body: "L’indirizzo non corrisponde a una pagina di FiscalBay.",
        back: "Torna agli ordini",
      },
    },
    skipToContent: "Vai al contenuto",
    mainNav: "Navigazione principale",
    orders: "Ordini",
    stores: "Negozi eBay",
    settings: "Impostazioni",
    search: "Cerca ordini",
    searchPlaceholder: "Ordine, acquirente, articolo o SKU",
    searchSeeAll: (count: number) => `Vedi tutti i risultati (${count})`,
    searchEmpty: "Nessun ordine corrisponde alla ricerca.",
    searchSummary: (count: number) =>
      count === 0
        ? "Nessun suggerimento"
        : `${count} ${plural(count, "suggerimento", "suggerimenti")}`,
    notifications: "Notifiche",
    notificationsUnread: (count: number) =>
      count === 0 ? "Notifiche" : `Notifiche, ${count} da leggere`,
    notificationsWindow: "Ultimi 30 giorni",
    notificationsEmpty: "Nessuna notifica negli ultimi 30 giorni.",
    markAllRead: "Segna tutte come lette",
    account: "Account",
    profile: "Profilo",
    security: "Sicurezza",
    planBilling: "Piano e pagamenti",
    visitSite: "Visita fiscalbay.it",
    signOut: "Esci",
    close: "Chiudi",
    back: "Indietro",
  },
  preview: {
    label: "Anteprima con dati di esempio",
    scenario: "Scenario",
    note: "Qui le azioni sono simulate e usano dati di esempio.",
    simulated: "Anteprima: l’azione è simulata.",
    signOut: "Anteprima: l’uscita è simulata.",
  },
  orders: {
    title: "Ordini",
    count: (count: number) => `${count} ${plural(count, "ordine", "ordini")}`,
    sortedBy: "Dal più recente",
    filters: "Filtri",
    store: "Negozio",
    marketplace: "Marketplace",
    period: "Periodo",
    paymentStatus: "Pagamento",
    shippingStatus: "Spedizione",
    fiscalStatus: "Codice Fiscale",
    all: "Tutti",
    last7: "Ultimi 7 giorni",
    last30: "Ultimi 30 giorni",
    last90: "Ultimi 90 giorni",
    searchActive: (query: string) => `Ricerca: ${query}`,
    clearSearch: "Cancella ricerca",
    resetFilters: "Reimposta filtri",
    premiumOption: "Disponibile con Premium",
    payment: { paid: "Pagato", unpaid: "Non pagato", refunded: "Rimborsato" },
    shipping: {
      to_ship: "Da spedire",
      shipped: "Spedito",
      delivered: "Consegnato",
      cancelled: "Annullato",
    },
    billingAddress: "Indirizzo di fatturazione",
    phone: "Telefono",
    email: "Email",
    notProvided: "Non riportato da eBay",
    fiscal: {
      available: "Disponibile",
      locked: "Da sbloccare",
      missing: "Non disponibile su eBay",
      checking: "In verifica",
      error: "Aggiornamento non riuscito",
    },
    select: "Seleziona",
    cancelSelection: "Annulla",
    selectOrder: (id: string) => `Seleziona l’ordine ${id}`,
    selected: (count: number) => `${count} ${plural(count, "selezionato", "selezionati")}`,
    selectedLocked: (count: number) =>
      count === 0
        ? "Nessun ordine da sbloccare"
        : `${count} ${plural(count, "ordine da sbloccare", "ordini da sbloccare")}`,
    unlock: "Sblocca ordine",
    unlockSelected: (count: number) => `Sblocca ${count}`,
    exportSelected: "Esporta",
    unlockTitle: (count: number) => `Sbloccare ${count} ${plural(count, "ordine", "ordini")}?`,
    unlockConfirmText: (count: number, remaining: number) =>
      `Dopo lo sblocco ${plural(remaining - count, "ti resterà", "ti resteranno")} ${remaining - count} ${plural(remaining - count, "ordine", "ordini")} da sbloccare in questo ciclo.`,
    unlockExceeds: (count: number, remaining: number) =>
      `Hai selezionato ${count} ordini da sbloccare, ma in questo ciclo te ne ${plural(remaining, "resta", "restano")} ${remaining}. Riduci la selezione.`,
    unlockConfirm: "Sblocca",
    cancel: "Annulla",
    unlocked: (remaining: number | null) =>
      remaining === null
        ? "Ordine sbloccato."
        : `Ordine sbloccato. ${plural(remaining, "Ti resta", "Ti restano")} ${remaining} ${plural(remaining, "ordine", "ordini")} da sbloccare.`,
    unlockedMany: (count: number) => `${count} ordini sbloccati.`,
    loadMore: "Carica altri",
    allShown: "Hai visto tutti gli ordini del periodo.",
    importMore: "Importazione in corso: gli altri ordini compaiono qui man mano.",
    details: "Dettaglio",
    moreActions: (id: string) => `Altre azioni per l’ordine ${id}`,
    openOnEbay: "Apri su eBay",
    exportOrder: "Esporta ordine",
    exportNotice: "Anteprima: l’esportazione non crea file.",
    items: (count: number) => `${count} ${plural(count, "articolo", "articoli")}`,
    itemsMore: (count: number) => `+ ${count} ${plural(count, "altro articolo", "altri articoli")}`,
    quantity: "Quantità",
    newOrders: (count: number) => `${count} ${plural(count, "nuovo ordine", "nuovi ordini")}`,
    showNew: "Mostra",
    identifier: { CF: "Codice Fiscale", PIVA: "Partita IVA" },
    copy: (label: string, order: string) => `Copia ${label}: ordine ${order}`,
    copied: "Copiato negli appunti",
    copyFailed: "Copia non riuscita. Riprova oppure seleziona e copia il codice.",
    lockedLabel: (label: string) => `${label} da sbloccare`,
    lockedHint: (remaining: number) =>
      `Hai ancora ${remaining} ${plural(remaining, "ordine disponibile", "ordini disponibili")}: dopo lo sblocco ${plural(remaining - 1, "ne resterà", "ne resteranno")} ${remaining - 1}.`,
    lockedExhausted: (date: string) =>
      `Hai sbloccato tutti gli ordini disponibili in questo ciclo. Il prossimo inizia il ${date}.`,
    lockedUntil: (date: string) => `Sblocco disponibile dal ${date}.`,
    missingHint: "eBay non riporta il Codice Fiscale per questo ordine.",
    checkingHint: "Verifica del Codice Fiscale in corso.",
    errorHint: "Non siamo riusciti a recuperare il Codice Fiscale da eBay. Riprova tra poco.",
    errorHintEbayDown:
      "Non siamo riusciti a recuperare il Codice Fiscale da eBay. Potrai riprovare quando eBay torna a rispondere.",
    retry: "Riprova",
    retried: "Nuova lettura richiesta.",
    quality: {
      format: "Il formato non corrisponde a un Codice Fiscale.",
      checksum: "Il carattere di controllo non corrisponde.",
      name: "Le lettere del codice non corrispondono al nome dell’ordine.",
      unverifiable: "Il nome non permette un controllo univoco del codice.",
      unchecked: "Tipo estero: FiscalBay non ne verifica il formato.",
    },
    toVerify: "Da verificare",
    updated: "Aggiornato da eBay",
    updatedHint: "eBay ha modificato questo dato dopo la prima lettura.",
    suggestion: "Suggerimento da un ordine precedente",
    suggestionFrom: "Da un ordine precedente:",
    suggestionCheck: "Controlla che valga anche per questo ordine.",
    suggestionHint: (order: string, date: string) => `Dall’ordine ${order} del ${date}.`,
    suggestionConflict: "Gli ordini precedenti riportano codici diversi: questo è il più recente.",
    requestMessage: "Copia messaggio per l’acquirente",
    requestCopied: "Messaggio copiato. Invialo all’acquirente dai tuoi canali.",
    syncedAgo: (time: string) => `Aggiornato ${time}`,
    refreshingTitle: "Aggiornamento in corso",
    ebayDownTitle: "eBay non risponde",
    ebayDownBody: (time: string) =>
      `Gli ordini sono aggiornati al ${time}. Sincronizzazione e ricollegamento tornano disponibili quando eBay risponde.`,
    quotaTitle: "Nessun ordine da sbloccare rimasto in questo ciclo",
    quotaBody: (date: string) =>
      `Puoi consultare e cercare tutti gli ordini. Il Codice Fiscale dei nuovi ordini resta da sbloccare fino al ${date}.`,
    quotaAction: "Scopri Premium",
    storeIssueTitle: (store: string) => `${store}: collegamento scaduto`,
    storeIssueBody:
      "La sincronizzazione di questo negozio è sospesa. Gli altri negozi continuano. Ricollega il negozio.",
    storeIssueAction: "Apri il negozio",
    importingStatus: (count: number) =>
      `Importazione in corso: ${count} ${plural(count, "ordine", "ordini")} finora`,
    firstUseTitle: "Nessun negozio collegato",
    firstUseBody:
      "Collega il tuo negozio eBay per consultare gli ordini e i Codici Fiscali disponibili.",
    connectStore: "Collega negozio eBay",
    steps: "Primi passi",
    stepAccount: "Account creato",
    stepEmail: "Email verificata",
    stepStore: "Negozio eBay collegato",
    stepSync: "Prima sincronizzazione",
    noOrdersTitle: "Nessun ordine negli ultimi 30 giorni",
    noOrdersBody: (store: string, time: string) =>
      `${store} è collegato e aggiornato al ${time}. I nuovi ordini compariranno qui.`,
    openStore: "Apri il negozio",
    noResultsTitle: "Nessun risultato",
    noResultsBody: "Nessun ordine corrisponde ai filtri. Modifica i criteri di ricerca.",
    noSearchResultsBody:
      "Nessun ordine corrisponde alla ricerca. Controlla il testo o cerca per numero d’ordine, acquirente, articolo o SKU.",
    loading: "Caricamento degli ordini",
    list: "Elenco ordini",
  },
  order: {
    title: (id: string) => `Ordine ${id}`,
    tabDetails: "Dettagli",
    tabItems: "Articoli",
    source: (time: string) => `Fonte: eBay, letto il ${time}`,
    buyer: "Acquirente",
    username: "Nome utente eBay",
    shipping: "Spedizione",
    recipient: "Destinatario",
    summary: "Ordine",
    total: "Totale",
    store: "Negozio",
    marketplace: "Marketplace",
    created: "Data ordine",
    update: "Aggiornamento",
    lastSynced: (time: string) => `Ultima lettura da eBay: ${time}`,
    sku: "SKU",
    noSku: "Senza SKU",
    price: "Prezzo",
  },
  stores: {
    title: "Negozi eBay",
    list: "Elenco negozi",
    connect: "Collega negozio eBay",
    store: "Negozio",
    marketplace: "Marketplace",
    connection: "Collegamento",
    lastSync: "Ultima sincronizzazione",
    openDetail: "Apri",
    notifications: "Notifiche",
    orders: "Ordini importati",
    state: {
      active: "Collegato",
      paused: "In pausa",
      reconnect_required: "Da ricollegare",
      error: "Autorizzazione incompleta",
    },
    syncing: "In sincronizzazione",
    never: "Mai",
    pausedByPlan: "In pausa per il piano Free",
    notificationsOn: "Attive",
    notificationsOff: "Disattivate",
    notificationsFree: "Le notifiche Telegram dei nuovi ordini sono disponibili con Premium.",
    freeLimit:
      "Con il piano Free hai un negozio attivo e puoi sostituirlo ogni 90 giorni. Gli altri restano in pausa e i loro ordini non sono consultabili.",
    open: (name: string) => `Apri ${name}`,
    sectionConnection: "Collegamento",
    sectionSync: "Sincronizzazione",
    sectionNotifications: "Notifiche",
    sectionRecent: "Ultimi aggiornamenti",
    sectionActions: "Azioni",
    account: "Account eBay",
    connectedSince: "Collegato dal",
    consentUntil: "Autorizzazione valida fino al",
    consentHint: "Prima della scadenza ti chiederemo di ricollegare il negozio.",
    consentExpired: "Scaduta",
    target: (minutes: number) => `Aggiornamento previsto circa ogni ${minutes} minuti`,
    history: (days: number) => `Storico degli ultimi ${days} giorni`,
    importDone: "Importazione dello storico completata",
    importRunning: "Importazione dello storico in corso",
    recentOk: (count: number) =>
      count === 0
        ? "Riuscito, nessun nuovo ordine"
        : `Riuscito, ${count} ${plural(count, "nuovo ordine", "nuovi ordini")}`,
    recentFailed: "Non riuscito",
    notificationsShortcut: "Le notifiche dei negozi si impostano in Impostazioni.",
    notificationsLink: "Apri le notifiche",
    syncNow: "Sincronizza ordini recenti",
    reimport: "Reimporta storico",
    pause: "Metti in pausa",
    resume: "Riprendi",
    pauseHint:
      "In pausa, FiscalBay non legge nuovi ordini. Quelli già importati restano consultabili.",
    planPauseHint:
      "Il piano Free include un solo negozio attivo. Scegli quale in Piano e pagamenti.",
    reconnect: "Ricollega negozio",
    disconnect: "Scollega",
    disconnectDelete: "Scollega ed elimina dati",
    disconnectTitle: (name: string) => `Scollegare ${name}?`,
    disconnectBody:
      "FiscalBay smette di leggere il negozio su eBay. Gli ordini già importati restano consultabili per il periodo di conservazione e puoi ricollegare lo stesso negozio in seguito.",
    deleteTitle: (name: string) => `Scollegare ed eliminare i dati di ${name}?`,
    deleteBody:
      "Il negozio viene scollegato e tutti i suoi ordini vengono eliminati da FiscalBay. L’operazione non si può annullare.",
    deleteLabel: "Scrivi il nome del negozio per confermare",
    deleteConfirm: "Scollega ed elimina",
    cancel: "Annulla",
    issue: {
      reconnect: {
        title: "Collegamento scaduto",
        body: "La sincronizzazione è sospesa. Ricollega il negozio.",
      },
      permissions: {
        title: "Autorizzazione incompleta",
        body: "eBay non ha concesso l’accesso agli ordini. Ricollega il negozio e accetta tutte le autorizzazioni richieste.",
      },
      unverifiable: {
        title: "Negozio non verificabile",
        body: "eBay non conferma l’identità di questo negozio. La sincronizzazione è sospesa. Ricollega il negozio. Se il problema continua, contatta l’assistenza.",
      },
    },
    elsewhereTitle: "Negozio già collegato a un altro account",
    elsewhereBody:
      "Questo negozio eBay è collegato a un altro account FiscalBay. Accedi con quell’account oppure contatta l’assistenza.",
    ebayDown: "eBay non risponde: sincronizzazione e ricollegamento sono sospesi.",
  },
  settings: {
    title: "Impostazioni",
    categories: "Categorie",
    sections: {
      piano: { title: "Piano e pagamenti", description: "Piano, ordini da sbloccare e pagamenti" },
      notifiche: { title: "Notifiche", description: "Telegram e comunicazioni" },
      esportazione: { title: "Esportazione", description: "File CSV e XLSX degli ordini" },
      sicurezza: { title: "Sicurezza", description: "Metodi di accesso e sessioni" },
      aspetto: { title: "Aspetto e lingua", description: "Tema, lingua e fuso orario" },
      messaggio: {
        title: "Modello di messaggio",
        description: "Richiesta del Codice Fiscale all’acquirente",
      },
      privacy: {
        title: "Dati e privacy",
        description: "Informativa, esportazione e cancellazione",
      },
      supporto: { title: "Supporto", description: "Domande frequenti e assistenza" },
    },
    premiumBadge: "Premium",
    saving: "Salvataggio…",
    saved: "Salvato",
    saveFailed: "Modifica non salvata. L’impostazione è tornata com’era: riprova.",
    save: "Salva",
    // Piano e pagamenti
    currentPlan: "Piano attuale",
    free: "Free",
    premium: "Premium",
    freeSummary: "Un negozio attivo, ultimi 30 giorni di ordini, CSV.",
    unlocksCycle: "Ordini sbloccati in questo ciclo",
    unlocksUsed: (used: number, limit: number) => `${used} di ${limit}`,
    cycleEnds: (date: string) => `Il ciclo si rinnova il ${date}.`,
    trialTitle: "Prova Premium per 14 giorni",
    trialBody:
      "Senza carta e senza rinnovo automatico. Alla fine della prova scegli tu se continuare con Premium.",
    trialAction: "Attiva la prova",
    buyTitle: "Passa a Premium",
    buyBody:
      "Ordini da sbloccare senza limite per ciclo, più negozi attivi, un anno di storico, XLSX e notifiche Telegram.",
    priceMonthly: "4,90 € al mese",
    priceAnnual: "49 € all’anno",
    priceLifetime: "149 € una tantum",
    priceMonthlyNote: "Si rinnova ogni mese.",
    priceAnnualNote: "Equivale a 4,08 € al mese.",
    priceLifetimeNote: "Pagamento unico, senza rinnovi.",
    pricesNote: "Prezzi IVA esclusa. Il pagamento avviene su Stripe.",
    buy: "Scegli",
    premiumPeriod: {
      monthly: "Premium mensile",
      annual: "Premium annuale",
      lifetime: "Premium a vita",
    },
    premiumLifetime: "Acquisto una tantum, senza rinnovi.",
    premiumRenews: (date: string) => `Si rinnova il ${date}.`,
    manageBilling: "Gestisci abbonamento su Stripe",
    billingDocs: "Ricevute e fatture sono disponibili su Stripe.",
    downgradeStore: "Negozio attivo se torni al piano Free",
    downgradeStoreHint:
      "Gli altri negozi andranno in pausa. Puoi cambiare scelta in qualsiasi momento.",
    // Notifiche
    telegramTitle: "Notifiche Telegram",
    telegramPremium: "Le notifiche degli ordini su Telegram sono incluse in Premium.",
    telegramChat: "Chat collegata",
    telegramChange: "Cambia chat",
    telegramEnabled: "Invia notifiche degli ordini",
    telegramFilter: "Quali ordini",
    telegramFilterAll: "Tutti i nuovi ordini",
    telegramFilterFiscal: "Solo ordini con Codice Fiscale",
    telegramMode: "Frequenza",
    telegramModeEach: "Un messaggio per ordine",
    telegramModeDigest: "Riepilogo giornaliero",
    telegramDigestTime: "Orario del riepilogo",
    telegramStores: "Negozi",
    marketingTitle: "Comunicazioni",
    marketingConsent: "Ricevi via email novità e offerte su FiscalBay",
    marketingHint: "Le email sul tuo account arrivano in ogni caso.",
    // Esportazione
    exportScope: "Ordini da esportare",
    exportPeriod: "Periodo",
    exportStores: "Negozi",
    exportFormat: "Formato",
    exportRows: "Una riga per",
    exportRowOrder: "Ordine",
    exportRowItem: "Articolo",
    exportColumns: "Colonne",
    exportColumnsPremium: "Colonne selezionabili e ordinabili con Premium.",
    exportPreview: (orders: number, locked: number) =>
      locked === 0
        ? `Circa ${orders} ordini.`
        : `Circa ${orders} ordini. Per ${locked} ${plural(locked, "ordine da sbloccare", "ordini da sbloccare")} il Codice Fiscale resta vuoto.`,
    exportCreate: "Crea file",
    exportCreated: "Anteprima: nessun file creato. Il file reale resta scaricabile per 24 ore.",
    exportSaveConfig: "Salva configurazione",
    columns: {
      order: "Numero ordine",
      date: "Data",
      buyer: "Acquirente",
      taxCode: "Codice Fiscale",
      vat: "Partita IVA",
      total: "Totale",
      store: "Negozio",
    },
    // Sicurezza
    methods: "Metodi di accesso",
    methodPassword: "Email e password",
    methodGoogle: "Google",
    methodEbay: "eBay",
    methodPasskey: "Passkey",
    methodConnected: "Collegato",
    methodNotConnected: "Non collegato",
    changePassword: "Cambia password",
    connect: "Collega",
    remove: "Rimuovi",
    addPasskey: "Aggiungi passkey",
    passkeyItem: (device: string, date: string) => `${device}, aggiunta il ${date}`,
    lastMethod: "Serve almeno un metodo di accesso.",
    sessions: "Sessioni attive",
    thisDevice: "Questo dispositivo",
    lastActive: (time: string) => `Ultima attività ${time}`,
    signOutSession: "Esci",
    signOutAll: "Esci da tutti gli altri dispositivi",
    // Aspetto e lingua
    theme: "Tema",
    themeSystem: "Sistema",
    themeLight: "Chiaro",
    themeDark: "Scuro",
    themeNote: "Nell’anteprima la scelta vale fino alla chiusura della pagina.",
    language: "Lingua",
    timeZone: "Fuso orario",
    timeZoneHint: "Usato per date, cicli e orari delle notifiche.",
    // Modello di messaggio
    templateIntro:
      "Quando eBay non riporta il Codice Fiscale, puoi copiare questo messaggio dall’ordine e inviarlo all’acquirente dai tuoi canali.",
    templateIt: "Italiano",
    templateEn: "Inglese",
    templateHint: "{ordine} viene sostituito con il numero dell’ordine.",
    templateDefaultIt:
      "Buongiorno e grazie per l’acquisto. Per emettere la fattura elettronica dell’ordine {ordine} ci serve il tuo Codice Fiscale. Se acquisti con Partita IVA, indicaci quella e la ragione sociale. Grazie.",
    templateDefaultEn:
      "Hello and thank you for your purchase. To issue the electronic invoice for order {ordine} we need your Italian tax code (Codice Fiscale). If you are buying with a VAT number, please send that and your company name instead. Thank you.",
    // Dati e privacy
    privacyPolicy: "Informativa privacy",
    privacyPolicyBody: "Quali dati trattiamo, per quanto tempo e con quali fornitori.",
    accountExport: "Esporta i dati dell’account",
    accountExportBody: "Profilo, negozi e impostazioni in un file scaricabile.",
    accountExportAction: "Richiedi esportazione",
    deleteAccount: "Elimina account",
    deleteAccountBody:
      "Elimina l’account, scollega i negozi e cancella gli ordini importati. Per confermare ti chiederemo di accedere di nuovo.",
    deleteAccountTitle: "Eliminare l’account?",
    deleteAccountConfirm: "Continua",
    // Supporto
    faq: "Domande frequenti",
    faqItems: [
      {
        q: "Perché un ordine non ha il Codice Fiscale?",
        a: "eBay non lo riporta per tutti gli ordini. Quando manca, puoi chiederlo all’acquirente con il modello di messaggio.",
      },
      {
        q: "Quando un ordine conta come sbloccato?",
        a: "Quando il suo Codice Fiscale diventa visibile. Ordini senza dato o con un errore non contano, e puoi copiare ed esportare quanto vuoi.",
      },
      {
        q: "FiscalBay modifica gli ordini su eBay?",
        a: "No. FiscalBay legge gli ordini per mostrarti i dati fiscali: sul tuo negozio eBay resta tutto com’è.",
      },
    ],
    contact: "Scrivi all’assistenza",
    topic: "Argomento",
    topics: {
      orders: "Ordini e Codice Fiscale",
      stores: "Collegamento negozi",
      billing: "Piano e pagamenti",
      other: "Altro",
    },
    message: "Messaggio",
    messageRequired: "Scrivi il messaggio.",
    diagnostics: "Riepilogo diagnostico",
    diagnosticsHint:
      "Aiuta l’assistenza a capire il problema. Contiene solo informazioni tecniche, come versione, stato della sincronizzazione e codice errore.",
    includeDiagnostics: "Allega il riepilogo diagnostico",
    diag: {
      version: "Versione",
      store: "Negozio",
      sync: "Sincronizzazione",
      error: "Codice errore",
      rights: "Piano",
      reference: "Riferimento",
      none: "Nessuno",
    },
    send: "Invia",
    sent: (email: string) => `Anteprima: richiesta non inviata. Ti risponderemmo a ${email}.`,
    formErrors: "Correggi i campi evidenziati.",
    supportEmail: "Puoi scrivere anche a supporto@fiscalbay.it.",
  },
  profile: {
    title: "Profilo",
    name: "Nome",
    nameHint: "Facoltativo. Compare nelle email di servizio.",
    email: "Email",
    emailHint: "Per cambiarla ti invieremo un link di verifica al nuovo indirizzo.",
    changeEmail: "Cambia email",
    security: "Metodi di accesso e sessioni sono in Sicurezza.",
    securityLink: "Apri Sicurezza",
    saved: "Anteprima: profilo non salvato.",
  },
  errors: {
    title: "Errore",
    notFoundTitle: "Pagina non trovata",
    notFound: "La pagina richiesta non è stata trovata.",
    home: "Torna a FiscalBay",
    unexpected: "Si è verificato un errore inatteso. Riprova più tardi.",
    reference: (id: string) => `Riferimento: ${id}`,
    codes: {
      AUTH_REQUIRED: "Accedi per continuare.",
      FORBIDDEN: "Non puoi eseguire questa operazione.",
      INVALID_REQUEST: "Controlla i dati e riprova.",
      UPSTREAM_UNAVAILABLE: "Servizio temporaneamente non disponibile. Riprova più tardi.",
      STORE_RECONNECT_REQUIRED: "Ricollega il negozio eBay e riprova.",
      CHECKOUT_PENDING: "Checkout non disponibile ora. Riprova più tardi.",
      INTERNAL_ERROR: "Operazione non riuscita. Riprova più tardi.",
    },
  },
  authError: {
    title: "Accesso non completato",
    body: "Riprova ad accedere. Se il problema continua, contatta il supporto.",
    back: "Torna a FiscalBay",
    ebayWithoutEmail: {
      title: "Accesso con eBay non disponibile",
      body: "eBay non ci fornisce l’indirizzo email del tuo account, come succede per gli account individuali. Accedi con email, Google o passkey: dopo potrai collegare il tuo negozio eBay.",
    },
    accountNotLinked: {
      title: "Email già registrata",
      body: "Esiste già un account FiscalBay con questo indirizzo email. Accedi con il metodo che usi di solito.",
    },
  },
  legal: {
    termini: "Termini di servizio",
    privacy: "Informativa privacy",
    version: (version: string) => `Versione ${version}`,
    draft:
      "Il testo definitivo sarà pubblicato prima dell’apertura del servizio. Se cambia, ti chiederemo di accettare la nuova versione.",
  },
  /** Pagina minima di accesso e ordini, finché le route reali non usano la shell. */
  access: {
    title: "Ordini",
    description: "Ordini eBay disponibili in FiscalBay",
    intro: "Trova e gestisci il Codice Fiscale dei tuoi ordini eBay.",
    headline: "Il Codice Fiscale dei tuoi ordini eBay, in un posto solo.",
    features: [
      {
        title: "Tutti gli ordini insieme",
        body: "Gli ordini dei tuoi negozi eBay in un unico elenco, aggiornato e facile da cercare.",
      },
      {
        title: "Pronto da copiare",
        body: "Trovi il Codice Fiscale riportato da eBay, o la Partita IVA se c’è solo quella, pronto da incollare dove ti serve.",
      },
      {
        title: "Collegamento in pochi passaggi",
        body: "Colleghi il negozio accedendo a eBay e gli ordini iniziano ad arrivare.",
      },
    ],
    choose: "Accedi o crea un account",
    language: "Lingua",
    email: "Email",
    password: "Password",
    signIn: "Accedi",
    signInBody: "Entra con email e password, Google, eBay o passkey.",
    signUp: "Crea account",
    signUpBody: "Bastano pochi dati per iniziare.",
    firstName: "Nome",
    lastName: "Cognome",
    accountType: "Ti registri come",
    private: "Privato",
    business: "Azienda",
    companyName: "Ragione sociale",
    accountTypeHint: "Piani e funzioni sono gli stessi per privati e aziende.",
    newPassword: "Password (almeno 8 caratteri)",
    or: "oppure",
    google: "Continua con Google",
    ebay: "Continua con eBay",
    ebayAccessTitle: "Accesso con eBay",
    ebayAccessBody: "Collega il tuo account eBay per usarlo come metodo di accesso a FiscalBay.",
    ebayAccessLink: "Collega accesso eBay",
    ebayAccessRemove: "Rimuovi accesso eBay",
    ebayAccessConnected: "Account eBay collegato come metodo di accesso.",
    passkeySignIn: "Accedi con passkey",
    passkeySecurity: "Sicurezza",
    passkeyRecovery:
      "Accedi con impronta, volto o blocco schermo del dispositivo. Se cambi dispositivo, aggiungi qui una nuova passkey.",
    passkeyLabel: "Passkey",
    passkeyAdd: "Aggiungi passkey",
    passkeyRemove: "Rimuovi",
    passkeyEmpty: "Nessuna passkey aggiunta.",
    passkeyFailed: "Operazione passkey non riuscita. Riprova sul tuo dispositivo.",
    passwordRecovery: "Hai dimenticato la password?",
    passwordRecoveryBody:
      "Inserisci l’email del tuo account: ti invieremo un link per scegliere una nuova password.",
    passwordRecoverySend: "Invia il link",
    passwordRecoveryConfirm: "Salva nuova password",
    signOut: "Esci",
    linkStore: "Collega negozio eBay",
    terms: {
      before: "Accetto i ",
      terms: "Termini di servizio",
      middle: " e ho letto l’",
      privacy: "Informativa privacy",
      after: ".",
    },
    marketing: "Ricevi via email novità e offerte su FiscalBay",
    marketingHint: "Facoltativo. Puoi cambiare scelta in Impostazioni.",
    agreementTitle: "Completa la registrazione",
    agreementBody: "Completa i dati mancanti per usare FiscalBay.",
    agreementSubmit: "Continua",
    verifyTitle: "Conferma l’indirizzo email",
    verifyBody: (email: string) =>
      `Abbiamo inviato un link a ${email}. Serve per collegare un negozio eBay. Intanto puoi esplorare FiscalBay.`,
    verifyResend: "Invia di nuovo il link",
    noOrders: "Nessun ordine",
    noOrdersBody: "Collega un negozio eBay per importare gli ordini disponibili.",
    noOrdersVerifyBody:
      "Dopo la conferma dell’indirizzo email potrai collegare un negozio eBay e importare gli ordini.",
    list: "Ordini qualificati",
    storeNotices: {
      collegato: "Negozio eBay collegato.",
      negato: "Collegamento annullato su eBay.",
      "altro-spazio": "Questo negozio eBay è già collegato a un altro account FiscalBay.",
      accesso: "Conferma l’indirizzo email per collegare un negozio.",
      errore: "Collegamento non riuscito. Riprova.",
    } as Record<string, string>,
    signInNotices: {
      "ebay-collegato": "Accesso eBay collegato al tuo account FiscalBay.",
      "ebay-rimosso": "Accesso eBay rimosso. I negozi collegati restano invariati.",
      "ultimo-metodo": "Aggiungi un altro metodo di accesso prima di rimuovere eBay.",
      "nuovo-accesso": "Per modificare i metodi di accesso, accedi di nuovo a FiscalBay.",
      "accesso-non-verificato": "Conferma l’indirizzo email per aggiungere un metodo di accesso.",
      errore: "Operazione non riuscita. Controlla email e password.",
      registrato: "Account creato. Ti abbiamo inviato un link per confermare l’indirizzo email.",
      registrazione:
        "Account non creato. Controlla email e password. Se sei già registrato, accedi.",
      termini: "Per continuare accetta i Termini di servizio.",
      dati: "Indica nome, cognome e, per un’azienda, la ragione sociale.",
      "troppi-tentativi": "Troppi tentativi. Riprova tra qualche minuto.",
      "verifica-inviata": "Link di conferma inviato. Controlla la posta.",
      "passkey-rimossa": "Passkey rimossa.",
      "ultimo-accesso": "Aggiungi un altro metodo di accesso prima di rimuovere questa passkey.",
      "recupero-inviato":
        "Controlla la posta: se l’indirizzo è registrato, trovi il link per scegliere una nuova password.",
      "password-reimpostata": "Password aggiornata. Accedi con la nuova password.",
      "recupero-scaduto": "Link non valido o scaduto. Richiedine uno nuovo.",
    } as Record<string, string>,
  },
};

export type AppCopy = typeof it;

const en: AppCopy = {
  shell: {
    notFound: {
      order: {
        title: "Order not found",
        body: "The order does not exist in this account or is no longer available.",
        back: "Back to orders",
      },
      store: {
        title: "Store not found",
        body: "The store is not connected to this account.",
        back: "Back to stores",
      },
      page: {
        title: "Page not found",
        body: "The address does not match a FiscalBay page.",
        back: "Back to orders",
      },
    },
    skipToContent: "Skip to content",
    mainNav: "Main navigation",
    orders: "Orders",
    stores: "eBay stores",
    settings: "Settings",
    search: "Search orders",
    searchPlaceholder: "Order, buyer, item or SKU",
    searchSeeAll: (count) => `See all results (${count})`,
    searchEmpty: "No orders match your search.",
    searchSummary: (count) =>
      count === 0 ? "No suggestions" : `${count} ${plural(count, "suggestion", "suggestions")}`,
    notifications: "Notifications",
    notificationsUnread: (count) =>
      count === 0 ? "Notifications" : `Notifications, ${count} unread`,
    notificationsWindow: "Last 30 days",
    notificationsEmpty: "No notifications in the last 30 days.",
    markAllRead: "Mark all as read",
    account: "Account",
    profile: "Profile",
    security: "Security",
    planBilling: "Plan and billing",
    visitSite: "Visit fiscalbay.it",
    signOut: "Sign out",
    close: "Close",
    back: "Back",
  },
  preview: {
    label: "Preview with sample data",
    scenario: "Scenario",
    note: "Actions here are simulated and use sample data.",
    simulated: "Preview: this action is simulated.",
    signOut: "Preview: signing out is simulated.",
  },
  orders: {
    title: "Orders",
    count: (count) => `${count} ${plural(count, "order", "orders")}`,
    sortedBy: "Newest first",
    filters: "Filters",
    store: "Store",
    marketplace: "Marketplace",
    period: "Period",
    paymentStatus: "Payment",
    shippingStatus: "Shipping",
    fiscalStatus: "Codice Fiscale",
    all: "All",
    last7: "Last 7 days",
    last30: "Last 30 days",
    last90: "Last 90 days",
    searchActive: (query) => `Search: ${query}`,
    clearSearch: "Clear search",
    resetFilters: "Reset filters",
    premiumOption: "Available with Premium",
    payment: { paid: "Paid", unpaid: "Unpaid", refunded: "Refunded" },
    shipping: {
      to_ship: "To ship",
      shipped: "Shipped",
      delivered: "Delivered",
      cancelled: "Cancelled",
    },
    billingAddress: "Billing address",
    phone: "Phone",
    email: "Email",
    notProvided: "Not provided by eBay",
    fiscal: {
      available: "Available",
      locked: "To unlock",
      missing: "Not available on eBay",
      checking: "Checking",
      error: "Couldn’t update",
    },
    select: "Select",
    cancelSelection: "Cancel",
    selectOrder: (id) => `Select order ${id}`,
    selected: (count) => `${count} selected`,
    selectedLocked: (count) =>
      count === 0
        ? "No orders to unlock"
        : `${count} ${plural(count, "order to unlock", "orders to unlock")}`,
    unlock: "Unlock order",
    unlockSelected: (count) => `Unlock ${count}`,
    exportSelected: "Export",
    unlockTitle: (count) => `Unlock ${count} ${plural(count, "order", "orders")}?`,
    unlockConfirmText: (count, remaining) =>
      `After unlocking, you can unlock ${remaining - count} more ${plural(remaining - count, "order", "orders")} this cycle.`,
    unlockExceeds: (count, remaining) =>
      `You selected ${count} orders to unlock, but you can unlock ${remaining} more ${plural(remaining, "order", "orders")} this cycle. Reduce the selection.`,
    unlockConfirm: "Unlock",
    cancel: "Cancel",
    unlocked: (remaining) =>
      remaining === null
        ? "Order unlocked."
        : `Order unlocked. You can unlock ${remaining} more ${plural(remaining, "order", "orders")}.`,
    unlockedMany: (count) => `${count} orders unlocked.`,
    loadMore: "Load more",
    allShown: "You have seen all orders in this period.",
    importMore: "Import in progress: the remaining orders will appear here as they arrive.",
    details: "Details",
    moreActions: (id) => `More actions for order ${id}`,
    openOnEbay: "Open on eBay",
    exportOrder: "Export order",
    exportNotice: "Preview: exporting does not create a file.",
    items: (count) => `${count} ${plural(count, "item", "items")}`,
    itemsMore: (count) => `+ ${count} more ${plural(count, "item", "items")}`,
    quantity: "Quantity",
    newOrders: (count) => `${count} new ${plural(count, "order", "orders")}`,
    showNew: "Show",
    identifier: { CF: "Codice Fiscale", PIVA: "Partita IVA" },
    copy: (label, order) => `Copy ${label}: order ${order}`,
    copied: "Copied to clipboard",
    copyFailed: "Copy failed. Try again, or select and copy the code.",
    lockedLabel: (label) => `${label} to unlock`,
    lockedHint: (remaining) =>
      `You have ${remaining} ${plural(remaining, "order", "orders")} left to unlock. After this one, you will have ${remaining - 1}.`,
    lockedExhausted: (date) =>
      `You have unlocked all available orders this cycle. The next one starts on ${date}.`,
    lockedUntil: (date) => `Unlocking available from ${date}.`,
    missingHint: "eBay does not provide the tax code for this order.",
    checkingHint: "Checking the tax code.",
    errorHint: "We could not get the tax code from eBay. Try again shortly.",
    errorHintEbayDown:
      "We could not get the tax code from eBay. You can try again once eBay responds.",
    retry: "Try again",
    retried: "New read requested.",
    quality: {
      format: "The format does not match an Italian tax code.",
      checksum: "The check character does not match.",
      name: "The letters of the code do not match the name on the order.",
      unverifiable: "The name does not allow an unambiguous check of the code.",
      unchecked: "Foreign type: FiscalBay does not check its format.",
    },
    toVerify: "Needs review",
    updated: "Updated by eBay",
    updatedHint: "eBay changed this value after it was first read.",
    suggestion: "Suggestion from a previous order",
    suggestionFrom: "From a previous order:",
    suggestionCheck: "Check that it also applies to this order.",
    suggestionHint: (order, date) => `From order ${order} on ${date}.`,
    suggestionConflict: "Previous orders show different codes: this is the most recent.",
    requestMessage: "Copy message for the buyer",
    requestCopied: "Message copied. Send it to the buyer through your own channels.",
    syncedAgo: (time) => `Updated ${time}`,
    refreshingTitle: "Updating",
    ebayDownTitle: "eBay is not responding",
    ebayDownBody: (time) =>
      `Orders are up to date as of ${time}. Syncing and reconnecting will be available again when eBay responds.`,
    quotaTitle: "No orders left to unlock this cycle",
    quotaBody: (date) =>
      `You can still view and search all orders. The tax code of new orders stays locked until ${date}.`,
    quotaAction: "Discover Premium",
    storeIssueTitle: (store) => `${store}: connection expired`,
    storeIssueBody: "Syncing is paused for this store. Other stores continue. Reconnect the store.",
    storeIssueAction: "Open store",
    importingStatus: (count) => `Importing: ${count} ${plural(count, "order", "orders")} so far`,
    firstUseTitle: "No store connected",
    firstUseBody: "Connect your eBay store to view orders and available tax codes.",
    connectStore: "Connect eBay store",
    steps: "Getting started",
    stepAccount: "Account created",
    stepEmail: "Email verified",
    stepStore: "eBay store connected",
    stepSync: "First sync",
    noOrdersTitle: "No orders in the last 30 days",
    noOrdersBody: (store, time) =>
      `${store} is connected and up to date as of ${time}. New orders will appear here.`,
    openStore: "Open store",
    noResultsTitle: "No results",
    noResultsBody: "No orders match the filters. Change your search criteria.",
    noSearchResultsBody:
      "No orders match the search. Check the text or search by order number, buyer, item or SKU.",
    loading: "Loading orders",
    list: "Order list",
  },
  order: {
    title: (id) => `Order ${id}`,
    tabDetails: "Details",
    tabItems: "Items",
    source: (time) => `Source: eBay, read on ${time}`,
    buyer: "Buyer",
    username: "eBay username",
    shipping: "Shipping",
    recipient: "Recipient",
    summary: "Order",
    total: "Total",
    store: "Store",
    marketplace: "Marketplace",
    created: "Order date",
    update: "Update",
    lastSynced: (time) => `Last read from eBay: ${time}`,
    sku: "SKU",
    noSku: "No SKU",
    price: "Price",
  },
  stores: {
    title: "eBay stores",
    list: "Store list",
    connect: "Connect eBay store",
    store: "Store",
    marketplace: "Marketplace",
    connection: "Connection",
    lastSync: "Last sync",
    openDetail: "Open",
    notifications: "Notifications",
    orders: "Imported orders",
    state: {
      active: "Connected",
      paused: "Paused",
      reconnect_required: "Reconnect needed",
      error: "Incomplete authorisation",
    },
    syncing: "Syncing",
    never: "Never",
    pausedByPlan: "Paused on the Free plan",
    notificationsOn: "On",
    notificationsOff: "Off",
    notificationsFree: "Telegram notifications for new orders are available with Premium.",
    freeLimit:
      "On the Free plan you have one active store, which you can replace every 90 days. Other stores stay paused and their orders are not available.",
    open: (name) => `Open ${name}`,
    sectionConnection: "Connection",
    sectionSync: "Sync",
    sectionNotifications: "Notifications",
    sectionRecent: "Recent updates",
    sectionActions: "Actions",
    account: "eBay account",
    connectedSince: "Connected since",
    consentUntil: "Authorisation valid until",
    consentHint: "Before it expires we will ask you to reconnect the store.",
    consentExpired: "Expired",
    target: (minutes) => `Expected update about every ${minutes} minutes`,
    history: (days) => `History of the last ${days} days`,
    importDone: "History import complete",
    importRunning: "History import in progress",
    recentOk: (count) =>
      count === 0
        ? "Succeeded, no new orders"
        : `Succeeded, ${count} new ${plural(count, "order", "orders")}`,
    recentFailed: "Failed",
    notificationsShortcut: "Store notifications are set in Settings.",
    notificationsLink: "Open notifications",
    syncNow: "Sync recent orders",
    reimport: "Re-import history",
    pause: "Pause",
    resume: "Resume",
    pauseHint: "While paused, FiscalBay reads no new orders. Imported orders remain available.",
    planPauseHint: "The Free plan includes one active store. Choose it in Plan and billing.",
    reconnect: "Reconnect store",
    disconnect: "Disconnect",
    disconnectDelete: "Disconnect and delete data",
    disconnectTitle: (name) => `Disconnect ${name}?`,
    disconnectBody:
      "FiscalBay will stop reading this store on eBay. Imported orders remain available for the retention period and you can reconnect the same store later.",
    deleteTitle: (name) => `Disconnect ${name} and delete its data?`,
    deleteBody:
      "The store is disconnected and all its orders are deleted from FiscalBay. This cannot be undone.",
    deleteLabel: "Type the store name to confirm",
    deleteConfirm: "Disconnect and delete",
    cancel: "Cancel",
    issue: {
      reconnect: {
        title: "Connection expired",
        body: "Syncing is paused. Reconnect the store.",
      },
      permissions: {
        title: "Incomplete authorisation",
        body: "eBay did not grant access to orders. Reconnect the store and accept all requested permissions.",
      },
      unverifiable: {
        title: "Store cannot be verified",
        body: "eBay does not confirm this store’s identity. Syncing is paused. Reconnect the store. If the problem continues, contact support.",
      },
    },
    elsewhereTitle: "Store already connected to another account",
    elsewhereBody:
      "This eBay store is connected to another FiscalBay account. Sign in with that account or contact support.",
    ebayDown: "eBay is not responding: syncing and reconnecting are paused.",
  },
  settings: {
    title: "Settings",
    categories: "Categories",
    sections: {
      piano: { title: "Plan and billing", description: "Plan, orders to unlock and payments" },
      notifiche: { title: "Notifications", description: "Telegram and communications" },
      esportazione: { title: "Export", description: "CSV and XLSX order files" },
      sicurezza: { title: "Security", description: "Sign-in methods and sessions" },
      aspetto: { title: "Appearance and language", description: "Theme, language and time zone" },
      messaggio: { title: "Message template", description: "Asking the buyer for the tax code" },
      privacy: { title: "Data and privacy", description: "Policy, export and deletion" },
      supporto: { title: "Support", description: "FAQ and help" },
    },
    premiumBadge: "Premium",
    saving: "Saving…",
    saved: "Saved",
    saveFailed: "Change not saved. The setting has been restored: try again.",
    save: "Save",
    currentPlan: "Current plan",
    free: "Free",
    premium: "Premium",
    freeSummary: "One active store, the last 30 days of orders, CSV.",
    unlocksCycle: "Orders unlocked this cycle",
    unlocksUsed: (used, limit) => `${used} of ${limit}`,
    cycleEnds: (date) => `The cycle renews on ${date}.`,
    trialTitle: "Try Premium for 14 days",
    trialBody:
      "No card and no automatic renewal. When the trial ends, you choose whether to keep Premium.",
    trialAction: "Start trial",
    buyTitle: "Upgrade to Premium",
    buyBody:
      "No limit on orders to unlock per cycle, more active stores, one year of history, XLSX and Telegram notifications.",
    priceMonthly: "€4.90 per month",
    priceAnnual: "€49 per year",
    priceLifetime: "€149 one-off",
    priceMonthlyNote: "Renews every month.",
    priceAnnualNote: "Works out at €4.08 per month.",
    priceLifetimeNote: "One-off payment, no renewals.",
    pricesNote: "Prices exclude VAT. Payment takes place on Stripe.",
    buy: "Choose",
    premiumPeriod: {
      monthly: "Premium, monthly",
      annual: "Premium, annual",
      lifetime: "Premium, lifetime",
    },
    premiumLifetime: "One-off purchase, no renewals.",
    premiumRenews: (date) => `Renews on ${date}.`,
    manageBilling: "Manage subscription on Stripe",
    billingDocs: "Receipts and invoices are available on Stripe.",
    downgradeStore: "Active store if you return to Free",
    downgradeStoreHint: "Other stores will be paused. You can change this at any time.",
    telegramTitle: "Telegram notifications",
    telegramPremium: "Order notifications on Telegram are included in Premium.",
    telegramChat: "Connected chat",
    telegramChange: "Change chat",
    telegramEnabled: "Send order notifications",
    telegramFilter: "Which orders",
    telegramFilterAll: "All new orders",
    telegramFilterFiscal: "Only orders with a tax code",
    telegramMode: "Frequency",
    telegramModeEach: "One message per order",
    telegramModeDigest: "Daily summary",
    telegramDigestTime: "Summary time",
    telegramStores: "Stores",
    marketingTitle: "Communications",
    marketingConsent: "Receive FiscalBay news and offers by email",
    marketingHint: "Emails about your account are always sent.",
    exportScope: "Orders to export",
    exportPeriod: "Period",
    exportStores: "Stores",
    exportFormat: "Format",
    exportRows: "One row per",
    exportRowOrder: "Order",
    exportRowItem: "Item",
    exportColumns: "Columns",
    exportColumnsPremium: "Choose and reorder columns with Premium.",
    exportPreview: (orders, locked) =>
      locked === 0
        ? `About ${orders} orders.`
        : `About ${orders} orders. For ${locked} ${plural(locked, "order", "orders")} to unlock, the tax code stays empty.`,
    exportCreate: "Create file",
    exportCreated: "Preview: no file created. A real file stays available for 24 hours.",
    exportSaveConfig: "Save configuration",
    columns: {
      order: "Order number",
      date: "Date",
      buyer: "Buyer",
      taxCode: "Codice Fiscale",
      vat: "Partita IVA",
      total: "Total",
      store: "Store",
    },
    methods: "Sign-in methods",
    methodPassword: "Email and password",
    methodGoogle: "Google",
    methodEbay: "eBay",
    methodPasskey: "Passkey",
    methodConnected: "Connected",
    methodNotConnected: "Not connected",
    changePassword: "Change password",
    connect: "Connect",
    remove: "Remove",
    addPasskey: "Add passkey",
    passkeyItem: (device, date) => `${device}, added on ${date}`,
    lastMethod: "At least one sign-in method is required.",
    sessions: "Active sessions",
    thisDevice: "This device",
    lastActive: (time) => `Last active ${time}`,
    signOutSession: "Sign out",
    signOutAll: "Sign out of all other devices",
    theme: "Theme",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    themeNote: "In the preview, the choice lasts until you close the page.",
    language: "Language",
    timeZone: "Time zone",
    timeZoneHint: "Used for dates, cycles and notification times.",
    templateIntro:
      "When eBay does not provide the tax code, you can copy this message from the order and send it to the buyer through your own channels.",
    templateIt: "Italian",
    templateEn: "English",
    templateHint: "{ordine} is replaced with the order number.",
    templateDefaultIt:
      "Buongiorno e grazie per l’acquisto. Per emettere la fattura elettronica dell’ordine {ordine} ci serve il tuo Codice Fiscale. Se acquisti con Partita IVA, indicaci quella e la ragione sociale. Grazie.",
    templateDefaultEn:
      "Hello and thank you for your purchase. To issue the electronic invoice for order {ordine} we need your Italian tax code (Codice Fiscale). If you are buying with a VAT number, please send that and your company name instead. Thank you.",
    privacyPolicy: "Privacy policy",
    privacyPolicyBody: "What data we process, for how long and with which providers.",
    accountExport: "Export account data",
    accountExportBody: "Profile, stores and settings in a downloadable file.",
    accountExportAction: "Request export",
    deleteAccount: "Delete account",
    deleteAccountBody:
      "Deletes the account, disconnects your stores and erases imported orders. To confirm, we will ask you to sign in again.",
    deleteAccountTitle: "Delete your account?",
    deleteAccountConfirm: "Continue",
    faq: "Frequently asked questions",
    faqItems: [
      {
        q: "Why does an order have no Codice Fiscale?",
        a: "eBay does not provide it for every order. When it is missing, you can ask the buyer with the message template.",
      },
      {
        q: "When does an order count as unlocked?",
        a: "When its tax code becomes visible. Orders without data or with an error do not count, and you can copy and export as often as you like.",
      },
      {
        q: "Does FiscalBay change orders on eBay?",
        a: "No. FiscalBay reads your orders to show you the tax details: everything on your eBay store stays as it is.",
      },
    ],
    contact: "Contact support",
    topic: "Topic",
    topics: {
      orders: "Orders and tax codes",
      stores: "Store connection",
      billing: "Plan and billing",
      other: "Other",
    },
    message: "Message",
    messageRequired: "Write your message.",
    diagnostics: "Diagnostic summary",
    diagnosticsHint:
      "Helps support understand the problem. It contains only technical details, such as version, sync status and error code.",
    includeDiagnostics: "Attach the diagnostic summary",
    diag: {
      version: "Version",
      store: "Store",
      sync: "Sync",
      error: "Error code",
      rights: "Plan",
      reference: "Reference",
      none: "None",
    },
    send: "Send",
    sent: (email) => `Preview: request not sent. We would reply to ${email}.`,
    formErrors: "Fix the highlighted fields.",
    supportEmail: "You can also write to supporto@fiscalbay.it.",
  },
  profile: {
    title: "Profile",
    name: "Name",
    nameHint: "Optional. Shown in service emails.",
    email: "Email",
    emailHint: "To change it, we will send a verification link to the new address.",
    changeEmail: "Change email",
    security: "Sign-in methods and sessions are in Security.",
    securityLink: "Open Security",
    saved: "Preview: profile not saved.",
  },
  errors: {
    title: "Error",
    notFoundTitle: "Page not found",
    notFound: "The requested page was not found.",
    home: "Back to FiscalBay",
    unexpected: "An unexpected error occurred. Try again later.",
    reference: (id) => `Reference: ${id}`,
    codes: {
      AUTH_REQUIRED: "Sign in to continue.",
      FORBIDDEN: "You cannot perform this operation.",
      INVALID_REQUEST: "Check your input and try again.",
      UPSTREAM_UNAVAILABLE: "Service temporarily unavailable. Try again later.",
      STORE_RECONNECT_REQUIRED: "Reconnect your eBay store and try again.",
      CHECKOUT_PENDING: "Checkout is unavailable right now. Try again later.",
      INTERNAL_ERROR: "The operation failed. Try again later.",
    },
  },
  authError: {
    title: "Sign in incomplete",
    body: "Try signing in again. If the problem continues, contact support.",
    back: "Back to FiscalBay",
    ebayWithoutEmail: {
      title: "Sign in with eBay unavailable",
      body: "eBay does not share the email address of your account, as happens with individual accounts. Sign in with email, Google or a passkey: you can then connect your eBay store.",
    },
    accountNotLinked: {
      title: "Email already registered",
      body: "A FiscalBay account already uses this email address. Sign in with the method you usually use.",
    },
  },
  legal: {
    termini: "Terms of service",
    privacy: "Privacy policy",
    version: (version: string) => `Version ${version}`,
    draft:
      "The final text will be published before the service opens. If it changes, we will ask you to accept the new version.",
  },
  access: {
    title: "Orders",
    description: "eBay orders available in FiscalBay",
    intro: "Find and manage the Italian tax code in your eBay orders.",
    headline: "The Codice Fiscale of your eBay orders, in one place.",
    features: [
      {
        title: "All your orders together",
        body: "Orders from your eBay stores in one list, up to date and easy to search.",
      },
      {
        title: "Ready to copy",
        body: "You find the tax code provided by eBay, or the VAT number if that is all it has, ready to paste wherever you need it.",
      },
      {
        title: "Connect in a few steps",
        body: "You connect a store by signing in to eBay, and orders start coming in.",
      },
    ],
    choose: "Sign in or create an account",
    language: "Language",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    signInBody: "Use your email and password, Google, eBay or a passkey.",
    signUp: "Create account",
    signUpBody: "It only takes a few details to get started.",
    firstName: "First name",
    lastName: "Last name",
    accountType: "You are registering as",
    private: "Individual",
    business: "Business",
    companyName: "Company name",
    accountTypeHint: "Plans and features are the same for individuals and businesses.",
    newPassword: "Password (at least 8 characters)",
    or: "or",
    google: "Continue with Google",
    ebay: "Continue with eBay",
    ebayAccessTitle: "Sign in with eBay",
    ebayAccessBody: "Link your eBay account to use it to sign in to FiscalBay.",
    ebayAccessLink: "Link eBay sign-in",
    ebayAccessRemove: "Remove eBay sign-in",
    ebayAccessConnected: "eBay account linked as a sign-in method.",
    passkeySignIn: "Sign in with a passkey",
    passkeySecurity: "Security",
    passkeyRecovery:
      "Sign in with your fingerprint, face or device screen lock. If you change device, add a new passkey here.",
    passkeyLabel: "Passkey",
    passkeyAdd: "Add passkey",
    passkeyRemove: "Remove",
    passkeyEmpty: "No passkeys added.",
    passkeyFailed: "Passkey operation failed. Try again on your device.",
    passwordRecovery: "Forgot your password?",
    passwordRecoveryBody:
      "Enter your account email and we will send you a link to set a new password.",
    passwordRecoverySend: "Send link",
    passwordRecoveryConfirm: "Save new password",
    signOut: "Sign out",
    linkStore: "Connect eBay store",
    terms: {
      before: "I accept the ",
      terms: "Terms of service",
      middle: " and I have read the ",
      privacy: "Privacy policy",
      after: ".",
    },
    marketing: "Receive FiscalBay news and offers by email",
    marketingHint: "Optional. You can change this in Settings.",
    agreementTitle: "Complete your registration",
    agreementBody: "Complete the missing details to use FiscalBay.",
    agreementSubmit: "Continue",
    verifyTitle: "Confirm your email address",
    verifyBody: (email: string) =>
      `We sent a link to ${email}. You need it to connect an eBay store. Meanwhile, you can explore FiscalBay.`,
    verifyResend: "Send the link again",
    noOrders: "No orders",
    noOrdersBody: "Connect an eBay store to import available orders.",
    noOrdersVerifyBody:
      "Once your email address is confirmed, you can connect an eBay store and import orders.",
    list: "Qualified orders",
    storeNotices: {
      collegato: "eBay store connected.",
      negato: "Connection cancelled on eBay.",
      "altro-spazio": "This eBay store is already connected to another FiscalBay account.",
      accesso: "Confirm your email address to connect a store.",
      errore: "Could not connect the store. Try again.",
    },
    signInNotices: {
      "ebay-collegato": "eBay sign-in linked to your FiscalBay account.",
      "ebay-rimosso": "eBay sign-in removed. Your connected stores are unchanged.",
      "ultimo-metodo": "Add another sign-in method before removing eBay.",
      "nuovo-accesso": "To change your sign-in methods, sign in to FiscalBay again.",
      "accesso-non-verificato": "Confirm your email address to add a sign-in method.",
      errore: "Could not complete the operation. Check your email and password.",
      registrato: "Account created. We sent you a link to confirm your email address.",
      registrazione:
        "Account not created. Check your email and password. If you already have an account, sign in.",
      termini: "To continue, accept the Terms of service.",
      dati: "Enter your first and last name and, for a business, the company name.",
      "troppi-tentativi": "Too many attempts. Try again in a few minutes.",
      "verifica-inviata": "Confirmation link sent. Check your inbox.",
      "passkey-rimossa": "Passkey removed.",
      "ultimo-accesso": "Add another sign-in method before removing this passkey.",
      "recupero-inviato":
        "Check your inbox: if the address is registered, you will find a link to set a new password.",
      "password-reimpostata": "Password updated. Sign in with your new password.",
      "recupero-scaduto": "This link is invalid or expired. Request a new one.",
    },
  },
};

export const appCopy: Record<Language, AppCopy> = { it, en };
